//======================================================================================
// Copyright 5AM Solutions Inc, Yale University, Lawrence Berkeley National Laboratory
//
// Distributed under the OSI-approved BSD 3-Clause License.
// See https://github.com/NCIP/caarray/blob/caRPLA/LICENSE for details.
//======================================================================================
package gov.nih.nci.carpla.rplatab.model;

import java.util.ArrayList;
import java.util.List;

/**
 * A <code>Source</code> is the original source material before any treatment
 * events. It is also a top node of the directed acyclic graph generated by
 * treatments.
 */
public final class Source extends AbstractBioMaterial
														implements
														SamplesSectionPrincipal,
														HasAttribute,
														HasProvider,
														HasName,
														HasCharacteristics {

	// need serial id
	private String		_name;

	// provider

	private Provider	_provider;

	public Provider getProvider () {
		return _provider;
	}

	public void setProvider ( Provider provider) {
		_provider = provider;
	}

	public String getName () {
		// TODO Auto-generated method stub
		return _name;
	}

	public void setName ( String name) {
		_name = name;
	}
	
	
	public String toString(){
		StringBuffer ret = new StringBuffer();
		ret.append("Source (name=");
		ret.append(getName()+")");
		return ret.toString();
		
	}
	
	
	
	

}
