SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS TERM;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS CATEGORYCHILDREN;
DROP TABLE IF EXISTS ACCESSION;
DROP TABLE IF EXISTS SOURCE;
DROP TABLE IF EXISTS PROTOCOLAPPLICATION;
DROP TABLE IF EXISTS PARAMETERVALUE;
DROP TABLE IF EXISTS PARAMETER;
DROP TABLE IF EXISTS PROTOCOL;

CREATE TABLE TERM
(
  ID                          INT UNSIGNED      NOT NULL,
  DESCRIPTION                 VARCHAR(1000),
  VALUE                       VARCHAR(1000),
  CATEGORY_ID                 INT UNSIGNED      NOT NULL,
  ACCESSION_ID                INT UNSIGNED,
  SOURCE_ID                   INT UNSIGNED,
  PRIMARY KEY                 (ID)
);

CREATE TABLE CATEGORY
(
  ID                          INT UNSIGNED      NOT NULL,
  NAME                        VARCHAR(1000),
  PARENT_ID                   INT UNSIGNED,
  PRIMARY KEY                 (ID)
);

CREATE TABLE CATEGORYCHILDREN
(
  CATEGORY_ID           INT UNSIGNED            NOT NULL,
  CHILD_CATEGORY_ID     INT UNSIGNED            NOT NULL,
  CONSTRAINT CATEGORYCHILDREN_PK PRIMARY KEY(CATEGORY_ID,CHILD_CATEGORY_ID)
);

CREATE TABLE ACCESSION
(
  ID                          INT UNSIGNED      NOT NULL,
  URL                         VARCHAR(1000),
  VALUE                       VARCHAR(1000),
  SOURCE_ID                   INT UNSIGNED      NOT NULL,
  PRIMARY KEY                 (ID)
);

CREATE TABLE SOURCE
(
  ID                          INT UNSIGNED      NOT NULL,
  NAME                        VARCHAR(1000),
  URL                         VARCHAR(1000),
  VERSION                     VARCHAR(1000),
  PRIMARY KEY                 (ID)
);

CREATE TABLE PROTOCOLAPPLICATION
(
  ID                          INT UNSIGNED      NOT NULL,
  PROTOCOL_ID                 INT UNSIGNED      NOT NULL,
  PRIMARY KEY                 (ID)
);

CREATE TABLE PARAMETERVALUE
(
  ID                          INT UNSIGNED      NOT NULL,
  UNIT                        VARCHAR(1000),
  VALUE                       VARCHAR(1000),
  PROTOCOL_APPLICATION_ID     INT UNSIGNED      NOT NULL,
  PARAMETER_ID                INT UNSIGNED      NOT NULL,
  PRIMARY KEY                 (ID)
);

CREATE TABLE PARAMETER
(
  ID                          INT UNSIGNED      NOT NULL,
  NAME                        VARCHAR(1000),
  PROTOCOL_ID                 INT UNSIGNED      NOT NULL,
  DEFAULT_VALUE_ID            INT UNSIGNED,
  PRIMARY KEY                 (ID)
);

CREATE TABLE PROTOCOL
(
  ID                          INT UNSIGNED      NOT NULL,
  ACCESSION                   VARCHAR(1000),
  NAME                        VARCHAR(1000),
  TEXT                        VARCHAR(1000),
  TITLE                       VARCHAR(1000),
  URL                         VARCHAR(1000),
  TYPE_ID                     INT UNSIGNED      NOT NULL,
  PRIMARY KEY                 (ID)
);

CREATE INDEX TERM_CATEGORY_IDX ON TERM(CATEGORY_ID);

CREATE INDEX TERM_ACCESSION_IDX ON TERM(ACCESSION_ID);

CREATE INDEX TERM_SOURCE_IDX ON TERM(SOURCE_ID);

CREATE INDEX CATEGORY_PARENT_IDX ON CATEGORY(PARENT_ID);

CREATE INDEX ACCESSION_SOURCE_IDX ON ACCESSION(SOURCE_ID);

CREATE INDEX PROTOCOLAPP_PROTOCOL ON PROTOCOLAPPLICATION(PROTOCOL_ID);

CREATE INDEX PARAMVALUE_PROTOCOLAPP_IDX ON PARAMETERVALUE(PROTOCOL_APPLICATION_ID);

CREATE INDEX PARAMVALUE_PARAMETER_IDX ON PARAMETERVALUE(PARAMETER_ID);

CREATE INDEX PARAMETER_PROTOCOL_IDX ON PARAMETER(PROTOCOL_ID);

CREATE INDEX PROTOCOL_TYPE_IDX ON PROTOCOL(TYPE_ID);

SET FOREIGN_KEY_CHECKS = 1;
