SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS TERM;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS ACCESSION;
DROP TABLE IF EXISTS SOURCE;
DROP TABLE IF EXISTS PROTOCOLAPPLICATION;
DROP TABLE IF EXISTS PARAMETERVALUE;
DROP TABLE IF EXISTS PARAMETER;
DROP TABLE IF EXISTS PROTOCOL;
DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS PERSONORGANIZATION;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS MEASUREMENT;
DROP TABLE IF EXISTS ARRAY;
DROP TABLE IF EXISTS ARRAYDESIGN;
DROP TABLE IF EXISTS REPORTERGROUP;
DROP TABLE IF EXISTS FEATUREGROUP;

CREATE TABLE TERM
(
  ID                          BIGINT      NOT NULL,
  DESCRIPTION                 VARCHAR(1000),
  VALUE                       VARCHAR(1000),
  CATEGORY_ID                 BIGINT      NOT NULL,
  ACCESSION_ID                BIGINT,
  SOURCE_ID                   BIGINT,
  PRIMARY KEY                 (ID)
);

CREATE TABLE CATEGORY
(
  ID                          BIGINT      NOT NULL,
  NAME                        VARCHAR(1000),
  PARENT_ID                   BIGINT,
  PRIMARY KEY                 (ID)
);

CREATE TABLE ACCESSION
(
  ID                          BIGINT      NOT NULL,
  URL                         VARCHAR(1000),
  VALUE                       VARCHAR(1000),
  SOURCE_ID                   BIGINT      NOT NULL,
  PRIMARY KEY                 (ID)
);

CREATE TABLE SOURCE
(
  ID                          BIGINT      NOT NULL,
  NAME                        VARCHAR(1000),
  URL                         VARCHAR(1000),
  VERSION                     VARCHAR(1000),
  PRIMARY KEY                 (ID)
);

CREATE TABLE PROTOCOLAPPLICATION
(
  ID                          BIGINT      NOT NULL,
  PROTOCOL_ID                 BIGINT      NOT NULL,
  PRIMARY KEY                 (ID)
);

CREATE TABLE PARAMETERVALUE
(
  ID                          BIGINT      NOT NULL,
  UNIT                        VARCHAR(1000),
  VALUE                       VARCHAR(1000),
  PROTOCOL_APPLICATION_ID     BIGINT,
  PARAMETER_ID                BIGINT      NOT NULL,
  PRIMARY KEY                 (ID)
);

CREATE TABLE PARAMETER
(
  ID                          BIGINT      NOT NULL,
  NAME                        VARCHAR(1000),
  PROTOCOL_ID                 BIGINT      NOT NULL,
  DEFAULT_VALUE_ID            BIGINT,
  PRIMARY KEY                 (ID)
);

CREATE TABLE PROTOCOL
(
  ID                          BIGINT      NOT NULL,
  NAME                        VARCHAR(1000),
  DESCRIPTION                 VARCHAR(1000),
  CONTACT                     VARCHAR(1000),
  HARDWARE                    VARCHAR(1000),
  SOFTWARE                    VARCHAR(1000),
  URL                         VARCHAR(1000),
  TYPE_ID                     BIGINT      NOT NULL,
  PRIMARY KEY                 (ID)
);

CREATE TABLE CONTACT
(
  ID                          BIGINT      NOT NULL,
  EMAIL                       VARCHAR(1000),
  FAX                         VARCHAR(1000),
  PHONE                       VARCHAR(1000),
  URL                         VARCHAR(1000),
  ADDRESS_ID                  BIGINT,
  DISCRIMINATOR               VARCHAR(5),
  NAME                        VARCHAR(1000),
  FIRSTNAME                   VARCHAR(1000),
  LASTNAME                    VARCHAR(1000),
  MIDDLEINITIAL               VARCHAR(20),
  PRIMARY KEY                 (ID)
);

CREATE TABLE PERSONORGANIZATION
(
  PERSON_ID                   BIGINT      NOT NULL,
  ORGANIZATION_ID             BIGINT      NOT NULL,
  PRIMARY KEY                 (PERSON_ID, ORGANIZATION_ID)
);

CREATE TABLE ADDRESS
(
  ID                          BIGINT      NOT NULL,
  CITY                        VARCHAR(1000),
  STATE                       VARCHAR(1000),
  STREETADDRESS1              VARCHAR(1000),
  STREETADDRESS2              VARCHAR(1000),
  ZIPCODE                     VARCHAR(20),
  PRIMARY KEY                 (ID)
);

CREATE TABLE MEASUREMENT
(
  ID                          BIGINT      NOT NULL,
  VALUE                       DECIMAL,
  PRIMARY KEY                 (ID)
);

CREATE TABLE ARRAY
(
  ID                          BIGINT      NOT NULL,
  BATCH                       VARCHAR(1000),
  SERIALNUMBER                VARCHAR(1000),
  DESIGN_ID                   BIGINT      NOT NULL,
  PRODUCTION_ID               BIGINT,
  PRIMARY KEY                 (ID)
);

CREATE TABLE ARRAYDESIGN
(
  ID                          BIGINT      NOT NULL,
  ACCESSION                   VARCHAR(1000),
  LENGTH_ID                   BIGINT,
  NAME                        VARCHAR(1000),
  NUMBEROFFEATURES            INT,
  SEQUENCEPOLYMERTYPE_ID      BIGINT,
  SUBSTRATETYPE_ID            BIGINT,
  SURFACETYPE_ID              BIGINT,
  TECHNOLOGYTYPE_ID           BIGINT,
  VERSION                     VARCHAR(1000),
  WIDTH_ID                    BIGINT,
  PRINTING_ID                 BIGINT,
  PROVIDER_ID                 BIGINT      NOT NULL,
  PRIMARY KEY                 (ID)
);

CREATE TABLE REPORTERGROUP
(
  ID                          BIGINT      NOT NULL,
  REPORTERTYPE_ID             BIGINT,
  STRANDTYPE_ID               BIGINT,
  ARRAYDESIGN_ID              BIGINT      NOT NULL,
  PRIMARY KEY                 (ID)
);

CREATE TABLE FEATUREGROUP
(
  ID                          BIGINT      NOT NULL,
  HEIGHT_ID                   BIGINT,
  LENGTH_ID                   BIGINT,
  WIDTH_ID                    BIGINT,
  ARRAYDESIGN_ID              BIGINT      NOT NULL,
  PRIMARY KEY                 (ID)
);

ALTER TABLE TERM
  ADD FOREIGN KEY(CATEGORY_ID)
  REFERENCES CATEGORY(ID);

ALTER TABLE TERM
  ADD FOREIGN KEY(ACCESSION_ID)
  REFERENCES ACCESSION(ID);

ALTER TABLE TERM
  ADD FOREIGN KEY(SOURCE_ID)
  REFERENCES SOURCE(ID);

ALTER TABLE CATEGORY
  ADD FOREIGN KEY(PARENT_ID)
  REFERENCES CATEGORY(ID);

ALTER TABLE ACCESSION
  ADD FOREIGN KEY(SOURCE_ID)
  REFERENCES SOURCE(ID);

ALTER TABLE PROTOCOLAPPLICATION
  ADD FOREIGN KEY(PROTOCOL_ID)
  REFERENCES PROTOCOL(ID);

ALTER TABLE PARAMETERVALUE
  ADD FOREIGN KEY(PROTOCOL_APPLICATION_ID)
  REFERENCES PROTOCOLAPPLICATION(ID);

ALTER TABLE PARAMETERVALUE
  ADD FOREIGN KEY(PARAMETER_ID)
  REFERENCES PARAMETER(ID);

ALTER TABLE PARAMETER
  ADD FOREIGN KEY(PROTOCOL_ID)
  REFERENCES PROTOCOL(ID);

ALTER TABLE PROTOCOL
  ADD FOREIGN KEY(TYPE_ID)
  REFERENCES TERM(ID);

ALTER TABLE CONTACT
  ADD FOREIGN KEY(ADDRESS_ID)
  REFERENCES ADDRESS(ID);

ALTER TABLE PERSONORGANIZATION
  ADD FOREIGN KEY(PERSON_ID)
  REFERENCES CONTACT(ID);

ALTER TABLE PERSONORGANIZATION
  ADD FOREIGN KEY(ORGANIZATION_ID)
  REFERENCES CONTACT(ID);

ALTER TABLE ARRAY
  ADD FOREIGN KEY(DESIGN_ID)
  REFERENCES ARRAYDESIGN(ID);

ALTER TABLE ARRAY
  ADD FOREIGN KEY(PRODUCTION_ID)
  REFERENCES PROTOCOLAPPLICATION(ID);

ALTER TABLE ARRAYDESIGN
  ADD FOREIGN KEY(LENGTH_ID)
  REFERENCES MEASUREMENT(ID);

ALTER TABLE ARRAYDESIGN
  ADD FOREIGN KEY(SEQUENCEPOLYMERTYPE_ID)
  REFERENCES TERM(ID);

ALTER TABLE ARRAYDESIGN
  ADD FOREIGN KEY(SUBSTRATETYPE_ID)
  REFERENCES TERM(ID);

ALTER TABLE ARRAYDESIGN
  ADD FOREIGN KEY(SURFACETYPE_ID)
  REFERENCES TERM(ID);

ALTER TABLE ARRAYDESIGN
  ADD FOREIGN KEY(TECHNOLOGYTYPE_ID)
  REFERENCES TERM(ID);

ALTER TABLE ARRAYDESIGN
  ADD FOREIGN KEY(WIDTH_ID)
  REFERENCES MEASUREMENT(ID);

ALTER TABLE ARRAYDESIGN
  ADD FOREIGN KEY(PRINTING_ID)
  REFERENCES PROTOCOLAPPLICATION(ID);

ALTER TABLE ARRAYDESIGN
  ADD FOREIGN KEY(PROVIDER_ID)
  REFERENCES CONTACT(ID);

ALTER TABLE REPORTERGROUP
  ADD FOREIGN KEY(REPORTERTYPE_ID)
  REFERENCES TERM(ID);

ALTER TABLE REPORTERGROUP
  ADD FOREIGN KEY(STRANDTYPE_ID)
  REFERENCES TERM(ID);

ALTER TABLE REPORTERGROUP
  ADD FOREIGN KEY(ARRAYDESIGN_ID)
  REFERENCES ARRAYDESIGN(ID);

ALTER TABLE FEATUREGROUP
  ADD FOREIGN KEY(HEIGHT_ID)
  REFERENCES MEASUREMENT(ID);

ALTER TABLE FEATUREGROUP
  ADD FOREIGN KEY(LENGTH_ID)
  REFERENCES MEASUREMENT(ID);

ALTER TABLE FEATUREGROUP
  ADD FOREIGN KEY(WIDTH_ID)
  REFERENCES MEASUREMENT(ID);

ALTER TABLE FEATUREGROUP
  ADD FOREIGN KEY(ARRAYDESIGN_ID)
  REFERENCES ARRAYDESIGN(ID);

CREATE INDEX TERM_CATEGORY_IDX ON TERM(CATEGORY_ID);

CREATE INDEX TERM_ACCESSION_IDX ON TERM(ACCESSION_ID);

CREATE INDEX TERM_SOURCE_IDX ON TERM(SOURCE_ID);

CREATE INDEX CATEGORY_PARENT_IDX ON CATEGORY(PARENT_ID);

CREATE INDEX ACCESSION_SOURCE_IDX ON ACCESSION(SOURCE_ID);

CREATE INDEX PROTOCOLAPP_PROTOCOL ON PROTOCOLAPPLICATION(PROTOCOL_ID);

CREATE INDEX PARAMVALUE_PROTOCOLAPP_IDX ON PARAMETERVALUE(PROTOCOL_APPLICATION_ID);

CREATE INDEX PARAMVALUE_PARAMETER_IDX ON PARAMETERVALUE(PARAMETER_ID);

CREATE INDEX PARAMETER_PROTOCOL_IDX ON PARAMETER(PROTOCOL_ID);

CREATE INDEX PROTOCOL_TYPE_IDX ON PROTOCOL(TYPE_ID);

CREATE INDEX CONTACT_ADDRESS_IDX ON CONTACT(ADDRESS_ID);

CREATE INDEX PERSONORG_PERSON_IDX ON PERSONORGANIZATION(PERSON_ID);

CREATE INDEX PERSONORG_ORG_IDX ON PERSONORGANIZATION(ORGANIZATION_ID);

CREATE INDEX ARRAY_DESIGN_IDX ON ARRAY(DESIGN_ID);

CREATE INDEX ARRAY_PRODUCTION_IDX ON ARRAY(PRODUCTION_ID);

CREATE INDEX ARRAYDESIGN_LENGTH_IDX ON ARRAYDESIGN(LENGTH_ID);

CREATE INDEX ARRAYDESIGN_SEQPOLYMER_IDX ON ARRAYDESIGN(SEQUENCEPOLYMERTYPE_ID);

CREATE INDEX ARRAYDESIGN_SUBSTRATE_IDX ON ARRAYDESIGN(SUBSTRATETYPE_ID);

CREATE INDEX ARRAYDESIGN_SURFACE_IDX ON ARRAYDESIGN(SURFACETYPE_ID);

CREATE INDEX ARRAYDESIGN_TECHNOLOGY_IDX ON ARRAYDESIGN(TECHNOLOGYTYPE_ID);

CREATE INDEX ARRAYDESIGN_WIDTH_IDX ON ARRAYDESIGN(WIDTH_ID);

CREATE INDEX ARRAYDESIGN_PRINTING_IDX ON ARRAYDESIGN(PRINTING_ID);

CREATE INDEX ARRAYDESIGN_PROVIDER_IDX ON ARRAYDESIGN(PROVIDER_ID);

CREATE INDEX REPORTERGROUP_REPORTER_IDX ON REPORTERGROUP(REPORTERTYPE_ID);

CREATE INDEX REPORTERGROUP_STRAND_IDX ON REPORTERGROUP(STRANDTYPE_ID);

CREATE INDEX REPORTERGROUP_DESIGN_IDX ON REPORTERGROUP(ARRAYDESIGN_ID);

CREATE INDEX FEATUREGROUP_HEIGHT_IDX ON FEATUREGROUP(HEIGHT_ID);

CREATE INDEX FEATUREGROUP_LENGTH_IDX ON FEATUREGROUP(LENGTH_ID);

CREATE INDEX FEATUREGROUP_WIDTH_IDX ON FEATUREGROUP(WIDTH_ID);

CREATE INDEX FEATUREGROUP_DESIGN_IDX ON FEATUREGROUP(ARRAYDESIGN_ID);

SET FOREIGN_KEY_CHECKS = 1;
