//============================================================================
// Copyright 5AM Solutions Inc, Yale University
//
// Distributed under the OSI-approved BSD 3-Clause License.
// See https://github.com/NCIP/caarray/blob/nimblegen-parser/LICENSE for details.
//============================================================================
package gov.nih.nci.cagrid.enumeration.service;

import  gov.nih.nci.caarray.services.external.v1_0.grid.service.CaArraySvc_v1_0Configuration;

import java.rmi.RemoteException;

import javax.naming.InitialContext;
import javax.xml.namespace.QName;

import org.apache.axis.MessageContext;
import org.globus.wsrf.Constants;
import org.globus.wsrf.ResourceContext;
import org.globus.wsrf.ResourceContextException;
import org.globus.wsrf.ResourceException;
import org.globus.wsrf.ResourceHome;
import org.globus.wsrf.ResourceProperty;
import org.globus.wsrf.ResourcePropertySet;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * Provides some simple accessors for the Impl.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public abstract class CaGridEnumerationImplBase {
	
	public CaGridEnumerationImplBase() throws RemoteException {
	
	}
	
	public CaArraySvc_v1_0Configuration getConfiguration() throws Exception {
		return CaArraySvc_v1_0Configuration.getConfiguration();
	}
	
	
	
	
	public gov.nih.nci.caarray.services.external.v1_0.grid.service.globus.resource.CaArraySvc_v1_0ResourceHome getCaArraySvc_v1_0ResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("caArraySvc_v1_0Home");
		return (gov.nih.nci.caarray.services.external.v1_0.grid.service.globus.resource.CaArraySvc_v1_0ResourceHome)resource;
	}
	
	
	protected ResourceHome getResourceHome(String resourceKey) throws Exception {
		MessageContext ctx = MessageContext.getCurrentContext();

		ResourceHome resourceHome = null;
		
		String servicePath = ctx.getTargetService();

		String jndiName = Constants.JNDI_SERVICES_BASE_NAME + servicePath + "/" + resourceKey;
		try {
			javax.naming.Context initialContext = new InitialContext();
			resourceHome = (ResourceHome) initialContext.lookup(jndiName);
		} catch (Exception e) {
			throw new Exception("Unable to instantiate resource home. : " + resourceKey, e);
		}

		return resourceHome;
	}


}

