package gov.nih.nci.cagrid.caarray.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public interface CaArrayGridServiceI {

    public gov.nih.nci.cagrid.metadata.security.ServiceSecurityMetadata getServiceSecurityMetadata() throws RemoteException ;

    public gov.nih.nci.caarray.domain.AbstractCaArrayEntity[] search(gov.nih.nci.caarray.domain.AbstractCaArrayEntity abstractCaArrayEntity) throws RemoteException ;

}

