package gov.nih.nci.cagrid.caarray.service.globus;

import gov.nih.nci.cagrid.caarray.service.CaArrayGridServiceImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the CaArrayGridServiceImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class CaArrayGridServiceProviderImpl{
	
	CaArrayGridServiceImpl impl;
	
	public CaArrayGridServiceProviderImpl() throws RemoteException {
		impl = new CaArrayGridServiceImpl();
	}
	

	public gov.nih.nci.cagrid.caarray.stubs.SearchResponse search(gov.nih.nci.cagrid.caarray.stubs.SearchRequest params) throws RemoteException {
		CaArrayGridServiceAuthorization.authorizeSearch();
		gov.nih.nci.cagrid.caarray.stubs.SearchResponse boxedResult = new gov.nih.nci.cagrid.caarray.stubs.SearchResponse();
		boxedResult.setAbstractCaArrayEntity(impl.search(params.getAbstractCaArrayEntity().getAbstractCaArrayEntity()));
		return boxedResult;
	}

}
