package gov.nih.nci.cagrid.caarray.service.globus;

import gov.nih.nci.cagrid.caarray.service.CaArraySvcImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the CaArraySvcImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public class CaArraySvcProviderImpl{
	
	CaArraySvcImpl impl;
	
	public CaArraySvcProviderImpl() throws RemoteException {
		impl = new CaArraySvcImpl();
	}
	

    public gov.nih.nci.cagrid.caarray.stubs.GetDesignDetailsResponse getDesignDetails(gov.nih.nci.cagrid.caarray.stubs.GetDesignDetailsRequest params) throws RemoteException {
    gov.nih.nci.cagrid.caarray.stubs.GetDesignDetailsResponse boxedResult = new gov.nih.nci.cagrid.caarray.stubs.GetDesignDetailsResponse();
    boxedResult.setArrayDesignDetails(impl.getDesignDetails(params.getArrayDesign().getArrayDesign()));
    return boxedResult;
  }

    public gov.nih.nci.cagrid.caarray.stubs.EchoResponse echo(gov.nih.nci.cagrid.caarray.stubs.EchoRequest params) throws RemoteException {
    gov.nih.nci.cagrid.caarray.stubs.EchoResponse boxedResult = new gov.nih.nci.cagrid.caarray.stubs.EchoResponse();
    boxedResult.setResponse(impl.echo(params.getString()));
    return boxedResult;
  }

    public gov.nih.nci.cagrid.caarray.stubs.ReadFileResponse readFile(gov.nih.nci.cagrid.caarray.stubs.ReadFileRequest params) throws RemoteException {
    gov.nih.nci.cagrid.caarray.stubs.ReadFileResponse boxedResult = new gov.nih.nci.cagrid.caarray.stubs.ReadFileResponse();
    boxedResult.setResponse(impl.readFile(params.getCaArrayFile().getCaArrayFile()));
    return boxedResult;
  }

    public gov.nih.nci.cagrid.caarray.stubs.GetDataSetForDerivedResponse getDataSetForDerived(gov.nih.nci.cagrid.caarray.stubs.GetDataSetForDerivedRequest params) throws RemoteException {
    gov.nih.nci.cagrid.caarray.stubs.GetDataSetForDerivedResponse boxedResult = new gov.nih.nci.cagrid.caarray.stubs.GetDataSetForDerivedResponse();
    boxedResult.setDataSet(impl.getDataSetForDerived(params.getDerivedArrayData().getDerivedArrayData()));
    return boxedResult;
  }

    public gov.nih.nci.cagrid.caarray.stubs.GetDataSetForRawResponse getDataSetForRaw(gov.nih.nci.cagrid.caarray.stubs.GetDataSetForRawRequest params) throws RemoteException {
    gov.nih.nci.cagrid.caarray.stubs.GetDataSetForRawResponse boxedResult = new gov.nih.nci.cagrid.caarray.stubs.GetDataSetForRawResponse();
    boxedResult.setDataSet(impl.getDataSetForRaw(params.getRawArrayData().getRawArrayData()));
    return boxedResult;
  }

}
