-- Placeholder file for caarray object populate
insert into category (name) value ('OrganismPart');
insert into category (name) value ('MaterialType');
insert into category (name) value ('CellType');
insert into category (name) value ('DiseaseState');
insert into category (name) value ('ExperimentDesignType');
insert into category (name) value ('QualityControlDescriptionType');
insert into category (name) value ('ReplicateDescriptionType');
insert into category (name) value ('Roles');
insert into category (name) value ('PublicationType');
insert into category (name) value ('PublicationStatus');
insert into category (name) value ('TechnologyType');

insert into termsource (name, url, version) values ('MGED', 'http://mged.sourceforge.net/ontologies/MGEDontology.php', '1.3.1.1');
insert into termsource (name, url, version) values ('Caarray', 'http://caarray.nci.nih.gov/ontologies/UserDefined.html', '0.1');

insert into term (value, source, category) select 'Brain', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='OrganismPart';
insert into term (value, source, category) select 'Leg', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='OrganismPart';
insert into term (value, source, category) select 'Feed', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='OrganismPart';
insert into term (value, source, category) select 'cell lysate', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='MaterialType';
insert into term (value, source, category) select 'total RNA', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='MaterialType';
insert into term (value, source, category) select 'DNA', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='MaterialType';
insert into term (value, source, category) select 'Brain Tissue', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='CellType';
insert into term (value, source, category) select 'Chromaphine Cells', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='CellType';
insert into term (value, source, category) select 'Adrenocortical Carcinoma', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='DiseaseState';
insert into term (value, source, category) select 'pharmacogenomic', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='ExperimentDesignType';
insert into term (value, source, category) select 'subclassification', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='ExperimentDesignType';
insert into term (value, source, category) select 'time_series_design', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='ExperimentDesignType';
insert into term (value, source, category) select 'biological_replicate', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='QualityControlDescriptionType';
insert into term (value, source, category) select 'dye_swap_quality_control', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='QualityControlDescriptionType';
insert into term (value, source, category) select 'peer_review_quality_control', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='QualityControlDescriptionType';
insert into term (value, source, category) select 'biological_replicate', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='ReplicateDescriptionType';
insert into term (value, source, category) select 'dye_swap_replicate', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='ReplicateDescriptionType';
insert into term (value, source, category) select 'technical_replicate', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='ReplicateDescriptionType';
insert into term (value, source, category) select 'investigator', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='Roles';
insert into term (value, source, category) select 'submitter', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='Roles';
insert into term (value, source, category) select 'Book', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='PublicationType';
insert into term (value, source, category) select 'Journal', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='PublicationType';
insert into term (value, source, category) select 'Review', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='PublicationType';
insert into term (value, source, category) select 'Submitted', termsource.id, category.id from termsource, category where termsource.name='Caarray' and category.name='PublicationStatus';
insert into term (value, source, category) select 'In Preparation', termsource.id, category.id from termsource, category where termsource.name='Caarray' and category.name='PublicationStatus';
insert into term (value, source, category) select 'Published', termsource.id, category.id from termsource, category where termsource.name='Caarray' and category.name='PublicationStatus';

-- TechnologyTypes
insert into term (value, source, category) select 'in_situ_oligo_features', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='TechnologyType';
insert into term (value, source, category) select 'spotted_antibody_features', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='TechnologyType';
insert into term (value, source, category) select 'spotted_colony_features', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='TechnologyType';
insert into term (value, source, category) select 'spotted_ds_DNA_features', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='TechnologyType';
insert into term (value, source, category) select 'spotted_protein_features', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='TechnologyType';
insert into term (value, source, category) select 'spotted_ss_PCR_amplicon_features', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='TechnologyType';
insert into term (value, source, category) select 'spotted_ss_oligo_features', termsource.id, category.id from termsource, category where termsource.name='MGED' and category.name='TechnologyType';

insert into organism (common_name, scientific_name, taxonomy_rank, ethnicity_strain) values ('Bovine', '', '', '');
insert into organism (common_name, scientific_name, taxonomy_Rank, ethnicity_Strain) values ('Canine', '', '', '');
insert into organism (common_name, scientific_name, taxonomy_Rank, ethnicity_Strain) values ('Chicken', '', '', '');
insert into organism (common_name, scientific_name, taxonomy_Rank, ethnicity_Strain) values ('Drosophila', '', '', '');
insert into organism (common_name, scientific_name, taxonomy_rank, ethnicity_strain) values ('E-coli', '', '', '');
insert into organism (common_name, scientific_name, taxonomy_Rank, ethnicity_Strain) values ('Homo Sapiens', '', '', '');
insert into organism (common_name, scientific_name, taxonomy_Rank, ethnicity_Strain) values ('Mouse', '', '', '');
insert into organism (common_name, scientific_name, taxonomy_Rank, ethnicity_Strain) values ('Plasmodium/Anopheles', '', '', '');
insert into organism (common_name, scientific_name, taxonomy_Rank, ethnicity_Strain) values ('Rat', '', '', '');
insert into organism (common_name, scientific_name, taxonomy_rank, ethnicity_strain) values ('S. Aureous', '', '', '');
insert into organism (common_name, scientific_name, taxonomy_Rank, ethnicity_Strain) values ('Songbird', '', '', '');
insert into organism (common_name, scientific_name, taxonomy_Rank, ethnicity_Strain) values ('Xenopus', '', '', '');
insert into organism (common_name, scientific_name, taxonomy_Rank, ethnicity_Strain) values ('Yeast', '', '', '');
insert into organism (common_name, scientific_name, taxonomy_rank, ethnicity_strain) values ('Zebra finch', '', '', '');
insert into organism (common_name, scientific_name, taxonomy_Rank, ethnicity_Strain) values ('Zebrafish', '', '', '');
 
insert into contact(discriminator, name) values ('O', 'Affymetrix');
insert into contact(discriminator, name) values ('O', 'Illumina');

insert into array_design(name, version, provider) select 'Sentrix', '1.0', id from contact where discriminator='O' and name='Affymetrix';
insert into array_design(name, version, provider) select 'Moohaa', '1.0', id from contact where discriminator='O' and name='Affymetrix';
insert into array_design(name, version, provider) select 'Ishtarti', '1.0', id from contact where discriminator='O' and name='Affymetrix';
insert into array_design(name, version, provider) select 'Illuminati', '1.0', id from contact where discriminator='O' and name='Illumina';
insert into array_design(name, version, provider) select 'Dojo', '1.0', id from contact where discriminator='O' and name='Illumina';

insert into country (code, name, printable_name, iso3, numcode) values ('AF','AFGHANISTAN','Afghanistan','AFG','004');
insert into country (code, name, printable_name, iso3, numcode) values ('AL','ALBANIA','Albania','ALB','008');
insert into country (code, name, printable_name, iso3, numcode) values ('DZ','ALGERIA','Algeria','DZA','012');
insert into country (code, name, printable_name, iso3, numcode) values ('AS','AMERICAN SAMOA','American Samoa','ASM','016');
insert into country (code, name, printable_name, iso3, numcode) values ('AD','ANDORRA','Andorra','AND','020');
insert into country (code, name, printable_name, iso3, numcode) values ('AO','ANGOLA','Angola','AGO','024');
insert into country (code, name, printable_name, iso3, numcode) values ('AI','ANGUILLA','Anguilla','AIA','660');
insert into country (code, name, printable_name, iso3, numcode) values ('AQ','ANTARCTICA','Antarctica',NULL,NULL);
insert into country (code, name, printable_name, iso3, numcode) values ('AG','ANTIGUA AND BARBUDA','Antigua and Barbuda','ATG','028');
insert into country (code, name, printable_name, iso3, numcode) values ('AR','ARGENTINA','Argentina','ARG','032');
insert into country (code, name, printable_name, iso3, numcode) values ('AM','ARMENIA','Armenia','ARM','051');
insert into country (code, name, printable_name, iso3, numcode) values ('AW','ARUBA','Aruba','ABW','533');
insert into country (code, name, printable_name, iso3, numcode) values ('AU','AUSTRALIA','Australia','AUS','036');
insert into country (code, name, printable_name, iso3, numcode) values ('AT','AUSTRIA','Austria','AUT','040');
insert into country (code, name, printable_name, iso3, numcode) values ('AZ','AZERBAIJAN','Azerbaijan','AZE','031');
insert into country (code, name, printable_name, iso3, numcode) values ('BS','BAHAMAS','Bahamas','BHS','044');
insert into country (code, name, printable_name, iso3, numcode) values ('BH','BAHRAIN','Bahrain','BHR','048');
insert into country (code, name, printable_name, iso3, numcode) values ('BD','BANGLADESH','Bangladesh','BGD','050');
insert into country (code, name, printable_name, iso3, numcode) values ('BB','BARBADOS','Barbados','BRB','052');
insert into country (code, name, printable_name, iso3, numcode) values ('BY','BELARUS','Belarus','BLR','112');
insert into country (code, name, printable_name, iso3, numcode) values ('BE','BELGIUM','Belgium','BEL','056');
insert into country (code, name, printable_name, iso3, numcode) values ('BZ','BELIZE','Belize','BLZ','084');
insert into country (code, name, printable_name, iso3, numcode) values ('BJ','BENIN','Benin','BEN','204');
insert into country (code, name, printable_name, iso3, numcode) values ('BM','BERMUDA','Bermuda','BMU','060');
insert into country (code, name, printable_name, iso3, numcode) values ('BT','BHUTAN','Bhutan','BTN','064');
insert into country (code, name, printable_name, iso3, numcode) values ('BO','BOLIVIA','Bolivia','BOL','068');
insert into country (code, name, printable_name, iso3, numcode) values ('BA','BOSNIA AND HERZEGOVINA','Bosnia and Herzegovina','BIH','070');
insert into country (code, name, printable_name, iso3, numcode) values ('BW','BOTSWANA','Botswana','BWA','072');
insert into country (code, name, printable_name, iso3, numcode) values ('BV','BOUVET ISLAND','Bouvet Island',NULL,NULL);
insert into country (code, name, printable_name, iso3, numcode) values ('BR','BRAZIL','Brazil','BRA','076');
insert into country (code, name, printable_name, iso3, numcode) values ('IO','BRITISH INDIAN OCEAN TERRITORY','British Indian Ocean Territory',NULL,NULL);
insert into country (code, name, printable_name, iso3, numcode) values ('BN','BRUNEI DARUSSALAM','Brunei Darussalam','BRN','096');
insert into country (code, name, printable_name, iso3, numcode) values ('BG','BULGARIA','Bulgaria','BGR','100');
insert into country (code, name, printable_name, iso3, numcode) values ('BF','BURKINA FASO','Burkina Faso','BFA','854');
insert into country (code, name, printable_name, iso3, numcode) values ('BI','BURUNDI','Burundi','BDI','108');
insert into country (code, name, printable_name, iso3, numcode) values ('KH','CAMBODIA','Cambodia','KHM','116');
insert into country (code, name, printable_name, iso3, numcode) values ('CM','CAMEROON','Cameroon','CMR','120');
insert into country (code, name, printable_name, iso3, numcode) values ('CA','CANADA','Canada','CAN','124');
insert into country (code, name, printable_name, iso3, numcode) values ('CV','CAPE VERDE','Cape Verde','CPV','132');
insert into country (code, name, printable_name, iso3, numcode) values ('KY','CAYMAN ISLANDS','Cayman Islands','CYM','136');
insert into country (code, name, printable_name, iso3, numcode) values ('CF','CENTRAL AFRICAN REPUBLIC','Central African Republic','CAF','140');
insert into country (code, name, printable_name, iso3, numcode) values ('TD','CHAD','Chad','TCD','148');
insert into country (code, name, printable_name, iso3, numcode) values ('CL','CHILE','Chile','CHL','152');
insert into country (code, name, printable_name, iso3, numcode) values ('CN','CHINA','China','CHN','156');
insert into country (code, name, printable_name, iso3, numcode) values ('CX','CHRISTMAS ISLAND','Christmas Island',NULL,NULL);
insert into country (code, name, printable_name, iso3, numcode) values ('CC','COCOS (KEELING) ISLANDS','Cocos (Keeling) Islands',NULL,NULL);
insert into country (code, name, printable_name, iso3, numcode) values ('CO','COLOMBIA','Colombia','COL','170');
insert into country (code, name, printable_name, iso3, numcode) values ('KM','COMOROS','Comoros','COM','174');
insert into country (code, name, printable_name, iso3, numcode) values ('CG','CONGO','Congo','COG','178');
insert into country (code, name, printable_name, iso3, numcode) values ('CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE','Congo, the Democratic Republic of the','COD','180');
insert into country (code, name, printable_name, iso3, numcode) values ('CK','COOK ISLANDS','Cook Islands','COK','184');
insert into country (code, name, printable_name, iso3, numcode) values ('CR','COSTA RICA','Costa Rica','CRI','188');
insert into country (code, name, printable_name, iso3, numcode) values ('CI','COTE D\'IVOIRE','Cote D\'Ivoire','CIV','384');
insert into country (code, name, printable_name, iso3, numcode) values ('HR','CROATIA','Croatia','HRV','191');
insert into country (code, name, printable_name, iso3, numcode) values ('CU','CUBA','Cuba','CUB','192');
insert into country (code, name, printable_name, iso3, numcode) values ('CY','CYPRUS','Cyprus','CYP','196');
insert into country (code, name, printable_name, iso3, numcode) values ('CZ','CZECH REPUBLIC','Czech Republic','CZE','203');
insert into country (code, name, printable_name, iso3, numcode) values ('DK','DENMARK','Denmark','DNK','208');
insert into country (code, name, printable_name, iso3, numcode) values ('DJ','DJIBOUTI','Djibouti','DJI','262');
insert into country (code, name, printable_name, iso3, numcode) values ('DM','DOMINICA','Dominica','DMA','212');
insert into country (code, name, printable_name, iso3, numcode) values ('DO','DOMINICAN REPUBLIC','Dominican Republic','DOM','214');
insert into country (code, name, printable_name, iso3, numcode) values ('EC','ECUADOR','Ecuador','ECU','218');
insert into country (code, name, printable_name, iso3, numcode) values ('EG','EGYPT','Egypt','EGY','818');
insert into country (code, name, printable_name, iso3, numcode) values ('SV','EL SALVADOR','El Salvador','SLV','222');
insert into country (code, name, printable_name, iso3, numcode) values ('GQ','EQUATORIAL GUINEA','Equatorial Guinea','GNQ','226');
insert into country (code, name, printable_name, iso3, numcode) values ('ER','ERITREA','Eritrea','ERI','232');
insert into country (code, name, printable_name, iso3, numcode) values ('EE','ESTONIA','Estonia','EST','233');
insert into country (code, name, printable_name, iso3, numcode) values ('ET','ETHIOPIA','Ethiopia','ETH','231');
insert into country (code, name, printable_name, iso3, numcode) values ('FK','FALKLAND ISLANDS (MALVINAS)','Falkland Islands (Malvinas)','FLK','238');
insert into country (code, name, printable_name, iso3, numcode) values ('FO','FAROE ISLANDS','Faroe Islands','FRO','234');
insert into country (code, name, printable_name, iso3, numcode) values ('FJ','FIJI','Fiji','FJI','242');
insert into country (code, name, printable_name, iso3, numcode) values ('FI','FINLAND','Finland','FIN','246');
insert into country (code, name, printable_name, iso3, numcode) values ('FR','FRANCE','France','FRA','250');
insert into country (code, name, printable_name, iso3, numcode) values ('GF','FRENCH GUIANA','French Guiana','GUF','254');
insert into country (code, name, printable_name, iso3, numcode) values ('PF','FRENCH POLYNESIA','French Polynesia','PYF','258');
insert into country (code, name, printable_name, iso3, numcode) values ('TF','FRENCH SOUTHERN TERRITORIES','French Southern Territories',NULL,NULL);
insert into country (code, name, printable_name, iso3, numcode) values ('GA','GABON','Gabon','GAB','266');
insert into country (code, name, printable_name, iso3, numcode) values ('GM','GAMBIA','Gambia','GMB','270');
insert into country (code, name, printable_name, iso3, numcode) values ('GE','GEORGIA','Georgia','GEO','268');
insert into country (code, name, printable_name, iso3, numcode) values ('DE','GERMANY','Germany','DEU','276');
insert into country (code, name, printable_name, iso3, numcode) values ('GH','GHANA','Ghana','GHA','288');
insert into country (code, name, printable_name, iso3, numcode) values ('GI','GIBRALTAR','Gibraltar','GIB','292');
insert into country (code, name, printable_name, iso3, numcode) values ('GR','GREECE','Greece','GRC','300');
insert into country (code, name, printable_name, iso3, numcode) values ('GL','GREENLAND','Greenland','GRL','304');
insert into country (code, name, printable_name, iso3, numcode) values ('GD','GRENADA','Grenada','GRD','308');
insert into country (code, name, printable_name, iso3, numcode) values ('GP','GUADELOUPE','Guadeloupe','GLP','312');
insert into country (code, name, printable_name, iso3, numcode) values ('GU','GUAM','Guam','GUM','316');
insert into country (code, name, printable_name, iso3, numcode) values ('GT','GUATEMALA','Guatemala','GTM','320');
insert into country (code, name, printable_name, iso3, numcode) values ('GN','GUINEA','Guinea','GIN','324');
insert into country (code, name, printable_name, iso3, numcode) values ('GW','GUINEA-BISSAU','Guinea-Bissau','GNB','624');
insert into country (code, name, printable_name, iso3, numcode) values ('GY','GUYANA','Guyana','GUY','328');
insert into country (code, name, printable_name, iso3, numcode) values ('HT','HAITI','Haiti','HTI','332');
insert into country (code, name, printable_name, iso3, numcode) values ('HM','HEARD ISLAND AND MCDONALD ISLANDS','Heard Island and Mcdonald Islands',NULL,NULL);
insert into country (code, name, printable_name, iso3, numcode) values ('VA','HOLY SEE (VATICAN CITY STATE)','Holy See (Vatican City State)','VAT','336');
insert into country (code, name, printable_name, iso3, numcode) values ('HN','HONDURAS','Honduras','HND','340');
insert into country (code, name, printable_name, iso3, numcode) values ('HK','HONG KONG','Hong Kong','HKG','344');
insert into country (code, name, printable_name, iso3, numcode) values ('HU','HUNGARY','Hungary','HUN','348');
insert into country (code, name, printable_name, iso3, numcode) values ('IS','ICELAND','Iceland','ISL','352');
insert into country (code, name, printable_name, iso3, numcode) values ('IN','INDIA','India','IND','356');
insert into country (code, name, printable_name, iso3, numcode) values ('ID','INDONESIA','Indonesia','IDN','360');
insert into country (code, name, printable_name, iso3, numcode) values ('IR','IRAN, ISLAMIC REPUBLIC OF','Iran, Islamic Republic of','IRN','364');
insert into country (code, name, printable_name, iso3, numcode) values ('IQ','IRAQ','Iraq','IRQ','368');
insert into country (code, name, printable_name, iso3, numcode) values ('IE','IRELAND','Ireland','IRL','372');
insert into country (code, name, printable_name, iso3, numcode) values ('IL','ISRAEL','Israel','ISR','376');
insert into country (code, name, printable_name, iso3, numcode) values ('IT','ITALY','Italy','ITA','380');
insert into country (code, name, printable_name, iso3, numcode) values ('JM','JAMAICA','Jamaica','JAM','388');
insert into country (code, name, printable_name, iso3, numcode) values ('JP','JAPAN','Japan','JPN','392');
insert into country (code, name, printable_name, iso3, numcode) values ('JO','JORDAN','Jordan','JOR','400');
insert into country (code, name, printable_name, iso3, numcode) values ('KZ','KAZAKHSTAN','Kazakhstan','KAZ','398');
insert into country (code, name, printable_name, iso3, numcode) values ('KE','KENYA','Kenya','KEN','404');
insert into country (code, name, printable_name, iso3, numcode) values ('KI','KIRIBATI','Kiribati','KIR','296');
insert into country (code, name, printable_name, iso3, numcode) values ('KP','KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF','Korea, Democratic People\'s Republic of','PRK','408');
insert into country (code, name, printable_name, iso3, numcode) values ('KR','KOREA, REPUBLIC OF','Korea, Republic of','KOR','410');
insert into country (code, name, printable_name, iso3, numcode) values ('KW','KUWAIT','Kuwait','KWT','414');
insert into country (code, name, printable_name, iso3, numcode) values ('KG','KYRGYZSTAN','Kyrgyzstan','KGZ','417');
insert into country (code, name, printable_name, iso3, numcode) values ('LA','LAO PEOPLE\'S DEMOCRATIC REPUBLIC','Lao People\'s Democratic Republic','LAO','418');
insert into country (code, name, printable_name, iso3, numcode) values ('LV','LATVIA','Latvia','LVA','428');
insert into country (code, name, printable_name, iso3, numcode) values ('LB','LEBANON','Lebanon','LBN','422');
insert into country (code, name, printable_name, iso3, numcode) values ('LS','LESOTHO','Lesotho','LSO','426');
insert into country (code, name, printable_name, iso3, numcode) values ('LR','LIBERIA','Liberia','LBR','430');
insert into country (code, name, printable_name, iso3, numcode) values ('LY','LIBYAN ARAB JAMAHIRIYA','Libyan Arab Jamahiriya','LBY','434');
insert into country (code, name, printable_name, iso3, numcode) values ('LI','LIECHTENSTEIN','Liechtenstein','LIE','438');
insert into country (code, name, printable_name, iso3, numcode) values ('LT','LITHUANIA','Lithuania','LTU','440');
insert into country (code, name, printable_name, iso3, numcode) values ('LU','LUXEMBOURG','Luxembourg','LUX','442');
insert into country (code, name, printable_name, iso3, numcode) values ('MO','MACAO','Macao','MAC','446');
insert into country (code, name, printable_name, iso3, numcode) values ('MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','Macedonia, the Former Yugoslav Republic of','MKD','807');
insert into country (code, name, printable_name, iso3, numcode) values ('MG','MADAGASCAR','Madagascar','MDG','450');
insert into country (code, name, printable_name, iso3, numcode) values ('MW','MALAWI','Malawi','MWI','454');
insert into country (code, name, printable_name, iso3, numcode) values ('MY','MALAYSIA','Malaysia','MYS','458');
insert into country (code, name, printable_name, iso3, numcode) values ('MV','MALDIVES','Maldives','MDV','462');
insert into country (code, name, printable_name, iso3, numcode) values ('ML','MALI','Mali','MLI','466');
insert into country (code, name, printable_name, iso3, numcode) values ('MT','MALTA','Malta','MLT','470');
insert into country (code, name, printable_name, iso3, numcode) values ('MH','MARSHALL ISLANDS','Marshall Islands','MHL','584');
insert into country (code, name, printable_name, iso3, numcode) values ('MQ','MARTINIQUE','Martinique','MTQ','474');
insert into country (code, name, printable_name, iso3, numcode) values ('MR','MAURITANIA','Mauritania','MRT','478');
insert into country (code, name, printable_name, iso3, numcode) values ('MU','MAURITIUS','Mauritius','MUS','480');
insert into country (code, name, printable_name, iso3, numcode) values ('YT','MAYOTTE','Mayotte',NULL,NULL);
insert into country (code, name, printable_name, iso3, numcode) values ('MX','MEXICO','Mexico','MEX','484');
insert into country (code, name, printable_name, iso3, numcode) values ('FM','MICRONESIA, FEDERATED STATES OF','Micronesia, Federated States of','FSM','583');
insert into country (code, name, printable_name, iso3, numcode) values ('MD','MOLDOVA, REPUBLIC OF','Moldova, Republic of','MDA','498');
insert into country (code, name, printable_name, iso3, numcode) values ('MC','MONACO','Monaco','MCO','492');
insert into country (code, name, printable_name, iso3, numcode) values ('MN','MONGOLIA','Mongolia','MNG','496');
insert into country (code, name, printable_name, iso3, numcode) values ('MS','MONTSERRAT','Montserrat','MSR','500');
insert into country (code, name, printable_name, iso3, numcode) values ('MA','MOROCCO','Morocco','MAR','504');
insert into country (code, name, printable_name, iso3, numcode) values ('MZ','MOZAMBIQUE','Mozambique','MOZ','508');
insert into country (code, name, printable_name, iso3, numcode) values ('MM','MYANMAR','Myanmar','MMR','104');
insert into country (code, name, printable_name, iso3, numcode) values ('NA','NAMIBIA','Namibia','NAM','516');
insert into country (code, name, printable_name, iso3, numcode) values ('NR','NAURU','Nauru','NRU','520');
insert into country (code, name, printable_name, iso3, numcode) values ('NP','NEPAL','Nepal','NPL','524');
insert into country (code, name, printable_name, iso3, numcode) values ('NL','NETHERLANDS','Netherlands','NLD','528');
insert into country (code, name, printable_name, iso3, numcode) values ('AN','NETHERLANDS ANTILLES','Netherlands Antilles','ANT','530');
insert into country (code, name, printable_name, iso3, numcode) values ('NC','NEW CALEDONIA','New Caledonia','NCL','540');
insert into country (code, name, printable_name, iso3, numcode) values ('NZ','NEW ZEALAND','New Zealand','NZL','554');
insert into country (code, name, printable_name, iso3, numcode) values ('NI','NICARAGUA','Nicaragua','NIC','558');
insert into country (code, name, printable_name, iso3, numcode) values ('NE','NIGER','Niger','NER','562');
insert into country (code, name, printable_name, iso3, numcode) values ('NG','NIGERIA','Nigeria','NGA','566');
insert into country (code, name, printable_name, iso3, numcode) values ('NU','NIUE','Niue','NIU','570');
insert into country (code, name, printable_name, iso3, numcode) values ('NF','NORFOLK ISLAND','Norfolk Island','NFK','574');
insert into country (code, name, printable_name, iso3, numcode) values ('MP','NORTHERN MARIANA ISLANDS','Northern Mariana Islands','MNP','580');
insert into country (code, name, printable_name, iso3, numcode) values ('NO','NORWAY','Norway','NOR','578');
insert into country (code, name, printable_name, iso3, numcode) values ('OM','OMAN','Oman','OMN','512');
insert into country (code, name, printable_name, iso3, numcode) values ('PK','PAKISTAN','Pakistan','PAK','586');
insert into country (code, name, printable_name, iso3, numcode) values ('PW','PALAU','Palau','PLW','585');
insert into country (code, name, printable_name, iso3, numcode) values ('PS','PALESTINIAN TERRITORY, OCCUPIED','Palestinian Territory, Occupied',NULL,NULL);
insert into country (code, name, printable_name, iso3, numcode) values ('PA','PANAMA','Panama','PAN','591');
insert into country (code, name, printable_name, iso3, numcode) values ('PG','PAPUA NEW GUINEA','Papua New Guinea','PNG','598');
insert into country (code, name, printable_name, iso3, numcode) values ('PY','PARAGUAY','Paraguay','PRY','600');
insert into country (code, name, printable_name, iso3, numcode) values ('PE','PERU','Peru','PER','604');
insert into country (code, name, printable_name, iso3, numcode) values ('PH','PHILIPPINES','Philippines','PHL','608');
insert into country (code, name, printable_name, iso3, numcode) values ('PN','PITCAIRN','Pitcairn','PCN','612');
insert into country (code, name, printable_name, iso3, numcode) values ('PL','POLAND','Poland','POL','616');
insert into country (code, name, printable_name, iso3, numcode) values ('PT','PORTUGAL','Portugal','PRT','620');
insert into country (code, name, printable_name, iso3, numcode) values ('PR','PUERTO RICO','Puerto Rico','PRI','630');
insert into country (code, name, printable_name, iso3, numcode) values ('QA','QATAR','Qatar','QAT','634');
insert into country (code, name, printable_name, iso3, numcode) values ('RE','REUNION','Reunion','REU','638');
insert into country (code, name, printable_name, iso3, numcode) values ('RO','ROMANIA','Romania','ROM','642');
insert into country (code, name, printable_name, iso3, numcode) values ('RU','RUSSIAN FEDERATION','Russian Federation','RUS','643');
insert into country (code, name, printable_name, iso3, numcode) values ('RW','RWANDA','Rwanda','RWA','646');
insert into country (code, name, printable_name, iso3, numcode) values ('SH','SAINT HELENA','Saint Helena','SHN','654');
insert into country (code, name, printable_name, iso3, numcode) values ('KN','SAINT KITTS AND NEVIS','Saint Kitts and Nevis','KNA','659');
insert into country (code, name, printable_name, iso3, numcode) values ('LC','SAINT LUCIA','Saint Lucia','LCA','662');
insert into country (code, name, printable_name, iso3, numcode) values ('PM','SAINT PIERRE AND MIQUELON','Saint Pierre and Miquelon','SPM','666');
insert into country (code, name, printable_name, iso3, numcode) values ('VC','SAINT VINCENT AND THE GRENADINES','Saint Vincent and the Grenadines','VCT','670');
insert into country (code, name, printable_name, iso3, numcode) values ('WS','SAMOA','Samoa','WSM','882');
insert into country (code, name, printable_name, iso3, numcode) values ('SM','SAN MARINO','San Marino','SMR','674');
insert into country (code, name, printable_name, iso3, numcode) values ('ST','SAO TOME AND PRINCIPE','Sao Tome and Principe','STP','678');
insert into country (code, name, printable_name, iso3, numcode) values ('SA','SAUDI ARABIA','Saudi Arabia','SAU','682');
insert into country (code, name, printable_name, iso3, numcode) values ('SN','SENEGAL','Senegal','SEN','686');
insert into country (code, name, printable_name, iso3, numcode) values ('CS','SERBIA AND MONTENEGRO','Serbia and Montenegro',NULL,NULL);
insert into country (code, name, printable_name, iso3, numcode) values ('SC','SEYCHELLES','Seychelles','SYC','690');
insert into country (code, name, printable_name, iso3, numcode) values ('SL','SIERRA LEONE','Sierra Leone','SLE','694');
insert into country (code, name, printable_name, iso3, numcode) values ('SG','SINGAPORE','Singapore','SGP','702');
insert into country (code, name, printable_name, iso3, numcode) values ('SK','SLOVAKIA','Slovakia','SVK','703');
insert into country (code, name, printable_name, iso3, numcode) values ('SI','SLOVENIA','Slovenia','SVN','705');
insert into country (code, name, printable_name, iso3, numcode) values ('SB','SOLOMON ISLANDS','Solomon Islands','SLB','090');
insert into country (code, name, printable_name, iso3, numcode) values ('SO','SOMALIA','Somalia','SOM','706');
insert into country (code, name, printable_name, iso3, numcode) values ('ZA','SOUTH AFRICA','South Africa','ZAF','710');
insert into country (code, name, printable_name, iso3, numcode) values ('GS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','South Georgia and the South Sandwich Islands',NULL,NULL);
insert into country (code, name, printable_name, iso3, numcode) values ('ES','SPAIN','Spain','ESP','724');
insert into country (code, name, printable_name, iso3, numcode) values ('LK','SRI LANKA','Sri Lanka','LKA','144');
insert into country (code, name, printable_name, iso3, numcode) values ('SD','SUDAN','Sudan','SDN','736');
insert into country (code, name, printable_name, iso3, numcode) values ('SR','SURINAME','Suriname','SUR','740');
insert into country (code, name, printable_name, iso3, numcode) values ('SJ','SVALBARD AND JAN MAYEN','Svalbard and Jan Mayen','SJM','744');
insert into country (code, name, printable_name, iso3, numcode) values ('SZ','SWAZILAND','Swaziland','SWZ','748');
insert into country (code, name, printable_name, iso3, numcode) values ('SE','SWEDEN','Sweden','SWE','752');
insert into country (code, name, printable_name, iso3, numcode) values ('CH','SWITZERLAND','Switzerland','CHE','756');
insert into country (code, name, printable_name, iso3, numcode) values ('SY','SYRIAN ARAB REPUBLIC','Syrian Arab Republic','SYR','760');
insert into country (code, name, printable_name, iso3, numcode) values ('TW','TAIWAN, PROVINCE OF CHINA','Taiwan, Province of China','TWN','158');
insert into country (code, name, printable_name, iso3, numcode) values ('TJ','TAJIKISTAN','Tajikistan','TJK','762');
insert into country (code, name, printable_name, iso3, numcode) values ('TZ','TANZANIA, UNITED REPUBLIC OF','Tanzania, United Republic of','TZA','834');
insert into country (code, name, printable_name, iso3, numcode) values ('TH','THAILAND','Thailand','THA','764');
insert into country (code, name, printable_name, iso3, numcode) values ('TL','TIMOR-LESTE','Timor-Leste',NULL,NULL);
insert into country (code, name, printable_name, iso3, numcode) values ('TG','TOGO','Togo','TGO','768');
insert into country (code, name, printable_name, iso3, numcode) values ('TK','TOKELAU','Tokelau','TKL','772');
insert into country (code, name, printable_name, iso3, numcode) values ('TO','TONGA','Tonga','TON','776');
insert into country (code, name, printable_name, iso3, numcode) values ('TT','TRINIDAD AND TOBAGO','Trinidad and Tobago','TTO','780');
insert into country (code, name, printable_name, iso3, numcode) values ('TN','TUNISIA','Tunisia','TUN','788');
insert into country (code, name, printable_name, iso3, numcode) values ('TR','TURKEY','Turkey','TUR','792');
insert into country (code, name, printable_name, iso3, numcode) values ('TM','TURKMENISTAN','Turkmenistan','TKM','795');
insert into country (code, name, printable_name, iso3, numcode) values ('TC','TURKS AND CAICOS ISLANDS','Turks and Caicos Islands','TCA','796');
insert into country (code, name, printable_name, iso3, numcode) values ('TV','TUVALU','Tuvalu','TUV','798');
insert into country (code, name, printable_name, iso3, numcode) values ('UG','UGANDA','Uganda','UGA','800');
insert into country (code, name, printable_name, iso3, numcode) values ('UA','UKRAINE','Ukraine','UKR','804');
insert into country (code, name, printable_name, iso3, numcode) values ('AE','UNITED ARAB EMIRATES','United Arab Emirates','ARE','784');
insert into country (code, name, printable_name, iso3, numcode) values ('GB','UNITED KINGDOM','United Kingdom','GBR','826');
insert into country (code, name, printable_name, iso3, numcode) values ('US','UNITED STATES','United States','USA','840');
insert into country (code, name, printable_name, iso3, numcode) values ('UM','UNITED STATES MINOR OUTLYING ISLANDS','United States Minor Outlying Islands',NULL,NULL);
insert into country (code, name, printable_name, iso3, numcode) values ('UY','URUGUAY','Uruguay','URY','858');
insert into country (code, name, printable_name, iso3, numcode) values ('UZ','UZBEKISTAN','Uzbekistan','UZB','860');
insert into country (code, name, printable_name, iso3, numcode) values ('VU','VANUATU','Vanuatu','VUT','548');
insert into country (code, name, printable_name, iso3, numcode) values ('VE','VENEZUELA','Venezuela','VEN','862');
insert into country (code, name, printable_name, iso3, numcode) values ('VN','VIET NAM','Viet Nam','VNM','704');
insert into country (code, name, printable_name, iso3, numcode) values ('VG','VIRGIN ISLANDS, BRITISH','Virgin Islands, British','VGB','092');
insert into country (code, name, printable_name, iso3, numcode) values ('VI','VIRGIN ISLANDS, U.S.','Virgin Islands, U.s.','VIR','850');
insert into country (code, name, printable_name, iso3, numcode) values ('WF','WALLIS AND FUTUNA','Wallis and Futuna','WLF','876');
insert into country (code, name, printable_name, iso3, numcode) values ('EH','WESTERN SAHARA','Western Sahara','ESH','732');
insert into country (code, name, printable_name, iso3, numcode) values ('YE','YEMEN','Yemen','YEM','887');
insert into country (code, name, printable_name, iso3, numcode) values ('ZM','ZAMBIA','Zambia','ZMB','894');
insert into country (code, name, printable_name, iso3, numcode) values ('ZW','ZIMBABWE','Zimbabwe','ZWE','716');
insert into state (name, code) values ('Alaska', 'AK');
insert into state (name, code) values ('Alabama', 'AL');
insert into state (name, code) values ('American Samoa', 'AS');
insert into state (name, code) values ('Arizona', 'AZ');
insert into state (name, code) values ('Arkansas', 'AR');
insert into state (name, code) values ('California', 'CA');
insert into state (name, code) values ('Colorado', 'CO');
insert into state (name, code) values ('Connecticut', 'CT');
insert into state (name, code) values ('Delaware', 'DE');
insert into state (name, code) values ('District of Columbia', 'DC');
insert into state (name, code) values ('Federated state of Micronesia', 'FM');
insert into state (name, code) values ('Florida', 'FL');
insert into state (name, code) values ('Georgia', 'GA');
insert into state (name, code) values ('Guam', 'GU');
insert into state (name, code) values ('Hawaii', 'HI');
insert into state (name, code) values ('Idaho', 'ID');
insert into state (name, code) values ('Illinois', 'IL');
insert into state (name, code) values ('Indiana', 'IN');
insert into state (name, code) values ('Iowa', 'IA');
insert into state (name, code) values ('Kansas', 'KS');
insert into state (name, code) values ('Kentucky', 'KY');
insert into state (name, code) values ('Louisiana', 'LA');
insert into state (name, code) values ('Maine', 'ME');
insert into state (name, code) values ('Marshall Islands', 'MH');
insert into state (name, code) values ('Maryland', 'MD');
insert into state (name, code) values ('Massachusetts', 'MA');
insert into state (name, code) values ('Michigan', 'MI');
insert into state (name, code) values ('Minnesota', 'MN');
insert into state (name, code) values ('Mississippi', 'MS');
insert into state (name, code) values ('Missouri', 'MO');
insert into state (name, code) values ('Montana', 'MT');
insert into state (name, code) values ('Nebraska', 'NE');
insert into state (name, code) values ('Nevada', 'NV');
insert into state (name, code) values ('New Hampshire', 'NH');
insert into state (name, code) values ('New Jersey', 'NJ');
insert into state (name, code) values ('New Mexico', 'NM');
insert into state (name, code) values ('New York', 'NY');
insert into state (name, code) values ('North Carolina', 'NC');
insert into state (name, code) values ('North Dakota', 'ND');
insert into state (name, code) values ('Northern Mariana Islands', 'MP');
insert into state (name, code) values ('Ohio', 'OH');
insert into state (name, code) values ('Oklahoma', 'OK');
insert into state (name, code) values ('Oregon', 'OR');
insert into state (name, code) values ('Palau', 'PW');
insert into state (name, code) values ('Pennsylvania', 'PA');
insert into state (name, code) values ('Puerto Rico', 'PR');
insert into state (name, code) values ('Rhode Island', 'RI');
insert into state (name, code) values ('South Carolina', 'SC');
insert into state (name, code) values ('South Dakota', 'SD');
insert into state (name, code) values ('Tennessee', 'TN');
insert into state (name, code) values ('Texas', 'TX');
insert into state (name, code) values ('Utah', 'UT');
insert into state (name, code) values ('Vermont', 'VT');
insert into state (name, code) values ('Virgin Islands', 'VI');
insert into state (name, code) values ('Virginia', 'VA');
insert into state (name, code) values ('Washington', 'WA');
insert into state (name, code) values ('West Virginia', 'WV');
insert into state (name, code) values ('Wisconsin', 'WI');
insert into state (name, code) values ('Wyoming', 'WY');
