package gov.nih.nci.cagrid.caarray.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;
import org.apache.axis.utils.ClassUtils;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import gov.nih.nci.cagrid.caarray.stubs.CaArrayGridServicePortType;
import gov.nih.nci.cagrid.caarray.stubs.service.CaArrayGridServiceAddressingLocator;
import gov.nih.nci.cagrid.caarray.common.CaArrayGridServiceI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;
import gov.nih.nci.caarray.domain.AbstractCaArrayEntity;
import gov.nih.nci.caarray.domain.vocabulary.Category;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.0
 */
public class CaArrayGridServiceClient extends ServiceSecurityClient implements CaArrayGridServiceI {	
	protected CaArrayGridServicePortType portType;
	private Object portTypeMutex;

	public CaArrayGridServiceClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public CaArrayGridServiceClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	   	initialize();
	}
	
	public CaArrayGridServiceClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public CaArrayGridServiceClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
		initialize();
	}
	
	private void initialize() throws RemoteException {
	    this.portTypeMutex = new Object();
		this.portType = createPortType();
	}

	private CaArrayGridServicePortType createPortType() throws RemoteException {

		CaArrayGridServiceAddressingLocator locator = new CaArrayGridServiceAddressingLocator();
		// attempt to load our context sensitive wsdd file
		InputStream resourceAsStream = ClassUtils.getResourceAsStream(getClass(), "client-config.wsdd");
		if (resourceAsStream != null) {
			// we found it, so tell axis to configure an engine to use it
			EngineConfiguration engineConfig = new FileProvider(resourceAsStream);
			// set the engine of the locator
			locator.setEngine(new AxisClient(engineConfig));
		}
		CaArrayGridServicePortType port = null;
		try {
			port = locator.getCaArrayGridServicePortTypePort(getEndpointReference());
		} catch (Exception e) {
			throw new RemoteException("Unable to locate portType:" + e.getMessage(), e);
		}

		return port;
	}
	
	public GetResourcePropertyResponse getResourceProperty(QName resourcePropertyQName) throws RemoteException {
		return portType.getResourceProperty(resourcePropertyQName);
	}

	public static void usage(){
		System.out.println(CaArrayGridServiceClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  CaArrayGridServiceClient client = new CaArrayGridServiceClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
				Category exampleCategory = new Category();
				exampleCategory.setName("DummyTestCategory4");
				AbstractCaArrayEntity[] retrievedCategories = client.search(exampleCategory);
				if(retrievedCategories == null) {
						System.out.println("No categories found.");
				} else {
						int numCategories = retrievedCategories.length;
						for (int i=0; i<numCategories; i++) {
							Category c = (Category) retrievedCategories[i];
								System.out.println("Found category: " + c.getName());
						}
				}
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

	public gov.nih.nci.cagrid.metadata.security.ServiceSecurityMetadata getServiceSecurityMetadata() throws RemoteException {
      synchronized(portTypeMutex){
        configureStubSecurity((Stub)portType,"getServiceSecurityMetadata");
        gov.nih.nci.cagrid.introduce.security.stubs.GetServiceSecurityMetadataRequest params = new gov.nih.nci.cagrid.introduce.security.stubs.GetServiceSecurityMetadataRequest();
        gov.nih.nci.cagrid.introduce.security.stubs.GetServiceSecurityMetadataResponse boxedResult = portType.getServiceSecurityMetadata(params);
        return boxedResult.getServiceSecurityMetadata();
      }
    }
	public gov.nih.nci.caarray.domain.AbstractCaArrayEntity[] search(gov.nih.nci.caarray.domain.AbstractCaArrayEntity abstractCaArrayEntity) throws RemoteException {
      synchronized(portTypeMutex){
        configureStubSecurity((Stub)portType,"search");
        gov.nih.nci.cagrid.caarray.stubs.SearchRequest params = new gov.nih.nci.cagrid.caarray.stubs.SearchRequest();
        gov.nih.nci.cagrid.caarray.stubs.SearchRequestAbstractCaArrayEntity abstractCaArrayEntityContainer = new gov.nih.nci.cagrid.caarray.stubs.SearchRequestAbstractCaArrayEntity();
        abstractCaArrayEntityContainer.setAbstractCaArrayEntity(abstractCaArrayEntity);
        params.setAbstractCaArrayEntity(abstractCaArrayEntityContainer);
        gov.nih.nci.cagrid.caarray.stubs.SearchResponse boxedResult = portType.search(params);
        return boxedResult.getAbstractCaArrayEntity();
      }
    }

}
