package gov.nih.nci.cagrid.caarray.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.4
 */
public interface CaArraySvcConstantsBase {
	public static final String SERVICE_NS = "http://caarray.cagrid.nci.nih.gov/CaArraySvc";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "CaArraySvcKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "CaArraySvcResourceProperties");
	public static final QName SERVICEMETADATA = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata", "ServiceMetadata");
	public static final QName DOMAINMODEL = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata.dataservice", "DomainModel");
	
}
