create table access_profile (id bigint not null auto_increment, security_level varchar(255) not null, group_id bigint, project_id bigint, primary key (id)) type=InnoDB;
create table access_profile_samples (access_profile_id bigint not null, security_level varchar(255), sample_id bigint not null, primary key (access_profile_id, sample_id)) type=InnoDB;
create table additional_organism_name (id bigint not null auto_increment, value varchar(255), comment varchar(255), source varchar(255), primary key (id)) type=InnoDB;
create table address (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), city varchar(254), street1 varchar(254), street2 varchar(254), zip_code varchar(254), state varchar(254), primary key (id)) type=InnoDB;
create table array (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), batch varchar(254), serial_number varchar(254), array_group bigint, design bigint, production bigint, primary key (id)) type=InnoDB;
create table array_data_type (id bigint not null auto_increment, bigid varchar(254), name varchar(254), version varchar(254), primary key (id)) type=InnoDB;
create table array_design (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), number_of_features integer, assay_type varchar(254) not null, name varchar(254) not null, version varchar(254) not null, description text, design_details bigint, technology_type bigint not null, printing bigint, polymer_type bigint, annotation_file bigint, organism bigint not null, surface_type bigint, substrate_type bigint, provider bigint not null, primary key (id), unique (name, provider)) type=InnoDB;
create table array_design_design_file (array_design bigint not null, design_file bigint not null, primary key (array_design, design_file)) type=InnoDB;
create table array_design_details (id bigint not null auto_increment, bigid varchar(254), primary key (id)) type=InnoDB;
create table array_group (id bigint not null auto_increment, bigid varchar(254), name varchar(255), primary key (id)) type=InnoDB;
create table arraydata (discriminator varchar(31) not null, id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), name varchar(254), data_file bigint not null, type bigint, data_set bigint, primary key (id)) type=InnoDB;
create table arraydatatype_quantitationtypes (arraydatatype_id bigint not null, quantitationtype_id bigint not null, primary key (arraydatatype_id, quantitationtype_id)) type=InnoDB;
create table arrayreporter (discriminator varchar(31) not null, id bigint not null auto_increment, bigid varchar(255), name varchar(255), strand varchar(255), probe_count bigint, probe_selection_region_id bigint, sequence_source varchar(255), sequence_type varchar(255), target_description varchar(255), target_id varchar(255), phast_conservation varchar(255), primary key (id)) type=InnoDB;
create table biomaterial (discriminator varchar(31) not null, id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), name varchar(254) not null, description varchar(254), external_sample_id varchar(254), organism bigint, label bigint, disease_state bigint, material_type bigint, tissue_site bigint, cell_type bigint, primary key (id)) type=InnoDB;
create table biomaterial_protocol_application (bio_material bigint not null, protocol_application bigint not null, protocol_order integer not null, primary key (bio_material, protocol_order)) type=InnoDB;
create table blob_holder (id bigint not null auto_increment, contents LONGBLOB, primary key (id)) type=InnoDB;
create table caarrayfile (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), uncompressed_size integer not null, name varchar(254), type varchar(254), compressed_size integer not null, status varchar(254), project bigint, validation_result bigint, primary key (id)) type=InnoDB;
create table caarrayfile_blob_parts (caarrayfile bigint not null, blob_parts bigint not null, contents_index integer not null, primary key (caarrayfile, contents_index), unique (blob_parts)) type=InnoDB;
create table category (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), url varchar(255), accession varchar(255), name varchar(254) not null, source bigint not null, primary key (id), unique (name, source), unique (accession, source)) type=InnoDB;
create table category_parents (category_id bigint not null, parent_category_id bigint not null, primary key (category_id, parent_category_id)) type=InnoDB;
create table characteristic (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), category bigint not null, bio_material bigint, primary key (id)) type=InnoDB;
create table characteristic_measurement (characteristic_id bigint not null, value float, unit bigint not null, primary key (characteristic_id)) type=InnoDB;
create table characteristic_term (characteristic_id bigint not null, term bigint not null, primary key (characteristic_id)) type=InnoDB;
create table collaborator_group (id bigint not null auto_increment, csm_group bigint not null, csm_user bigint not null, primary key (id), unique (csm_group, csm_user)) type=InnoDB;
create table contact (discriminator varchar(31) not null, id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), url varchar(254), email varchar(254), fax varchar(254), phone varchar(254), provider bit, name varchar(254), first_name varchar(254), last_name varchar(254), middle_initials varchar(254), address bigint, primary key (id)) type=InnoDB;
create table country (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), code varchar(255) unique, printable_name varchar(255), iso3 varchar(255) unique, numcode varchar(255), name varchar(255), primary key (id)) type=InnoDB;
create table data_set (id bigint not null auto_increment, bigid varchar(254), design_element_list bigint, primary key (id)) type=InnoDB;
create table data_set_hybridization_data_list (data_set bigint not null, hybridization_data_list bigint not null, hybridization_index integer not null, primary key (data_set, hybridization_index), unique (hybridization_data_list)) type=InnoDB;
create table datacolumn (discriminator varchar(31) not null, id bigint not null auto_increment, bigid varchar(254), hybridization_data bigint not null, quantitation_type bigint, primary key (id)) type=InnoDB;
create table datacolumn_blob_parts (datacolumn bigint not null, blob_parts bigint not null, contents_index integer not null, primary key (datacolumn, contents_index), unique (blob_parts)) type=InnoDB;
create table datasetquantitationtype (dataset_id bigint not null, quantitationtype_id bigint not null, quantitationtype_index integer not null, primary key (dataset_id, quantitationtype_index)) type=InnoDB;
create table derivedarraydata_derivedfrom (derivedarraydata_id bigint not null, derivedfrom_arraydata_id bigint not null, primary key (derivedarraydata_id, derivedfrom_arraydata_id)) type=InnoDB;
create table derivedarraydata_hybridizations (derivedarraydata_id bigint not null, hybridization_id bigint not null, primary key (derivedarraydata_id, hybridization_id)) type=InnoDB;
create table design_element (discriminator varchar(31) not null, id bigint not null auto_increment, bigid varchar(254), name varchar(255), feature_row smallint, block_column smallint, block_row smallint, feature_column smallint, probe_group bigint, physicalprobe_details_id bigint, feature_details_id bigint, control_type bigint, annotation bigint, logicalprobe_details_id bigint, primary key (id)) type=InnoDB;
create table design_element_list (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), design_element_type varchar(255), primary key (id), unique (lsid_authority, lsid_namespace, lsid_object_id)) type=InnoDB;
create table designelementlist_designelement (designelementlist_id bigint not null, designelement_id bigint not null, designelement_index integer not null, primary key (designelementlist_id, designelement_index)) type=InnoDB;
create table experiment (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), assay_type varchar(254) not null, public_release_date datetime, public_identifier varchar(254), payment_number varchar(100), service_type varchar(255) not null, experiment_design_description text, quality_control_description text, replicate_description text, date_of_experiment datetime, title varchar(254) not null, description text, manufacturer bigint not null, organism bigint not null, payment_mechanism bigint, primary key (id), unique (public_identifier)) type=InnoDB;
create table experiment_contact (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), contact bigint, experiment bigint, indx integer, primary key (id)) type=InnoDB;
create table experiment_design_types (experiment_id bigint not null, term_id bigint not null, primary key (experiment_id, term_id)) type=InnoDB;
create table experimentarraydesign (experiment_id bigint not null, arraydesign_id bigint not null, primary key (experiment_id, arraydesign_id)) type=InnoDB;
create table experimentcontactrole (experimentcontact_id bigint not null, role_id bigint not null, primary key (experimentcontact_id, role_id)) type=InnoDB;
create table experimentextract (extract_id bigint not null, experiment_id bigint, primary key (experiment_id, extract_id), unique (extract_id)) type=InnoDB;
create table experimentlabeledextract (labeled_extract_id bigint not null, experiment_id bigint, primary key (experiment_id, labeled_extract_id), unique (labeled_extract_id)) type=InnoDB;
create table experimentsample (sample_id bigint not null, experiment_id bigint, primary key (experiment_id, sample_id), unique (sample_id)) type=InnoDB;
create table experimentsource (source_id bigint not null, experiment_id bigint, primary key (experiment_id, source_id), unique (source_id)) type=InnoDB;
create table extractlabeledextract (extract_id bigint not null, labeledextract_id bigint not null, primary key (extract_id, labeledextract_id)) type=InnoDB;
create table factor (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), name varchar(254) not null, description text, experiment bigint, type bigint not null, primary key (id)) type=InnoDB;
create table factor_value (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), value varchar(254), unit bigint, factor bigint, hybridization bigint, primary key (id)) type=InnoDB;
create table file_validation_result (id bigint not null auto_increment, primary key (id)) type=InnoDB;
create table file_validation_result_message_set (file_validation_result bigint not null, message_set bigint not null, primary key (file_validation_result, message_set), unique (message_set)) type=InnoDB;
create table gene (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), ensemblgeneid varchar(255), entrezgeneid varchar(255), genbank_accession varchar(255), genbank_accession_version varchar(255), unigeneclusterid varchar(255), full_name text, symbol varchar(255), primary key (id)) type=InnoDB;
create table hybridization (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), amount_of_material float, name varchar(254) not null, description varchar(254), experiment bigint, array bigint, amount_of_material_unit bigint, primary key (id), unique (name, experiment)) type=InnoDB;
create table hybridization_data (id bigint not null auto_increment, bigid varchar(254), labeled_extract bigint, hybridization bigint, data_set bigint not null, primary key (id)) type=InnoDB;
create table hybridization_data_columns (hybridization_data bigint not null, columns bigint not null, column_index integer not null, primary key (hybridization_data, column_index), unique (columns)) type=InnoDB;
create table hybridization_protocol_application (hybridization bigint not null, protocol_application bigint not null, protocol_order integer not null, primary key (hybridization, protocol_order)) type=InnoDB;
create table image (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), name varchar(254) not null, image_file bigint, raw_array_data bigint, hybridization bigint, primary key (id)) type=InnoDB;
create table labeledextracthybridization (labeledextract_id bigint not null, hybridization_id bigint not null, primary key (labeledextract_id, hybridization_id)) type=InnoDB;
create table logicalprobe_physicalprobe (logical_probe_id bigint not null, physical_probe_id bigint not null, primary key (logical_probe_id, physical_probe_id)) type=InnoDB;
create table normalizationtype (experiment_id bigint not null, term_id bigint not null, primary key (experiment_id, term_id)) type=InnoDB;
create table organism (id bigint not null auto_increment, common_name varchar(255), ethnicity_strain varchar(255), ncbi_taxonomy_id bigint, scientific_name varchar(254) not null, taxonomy_rank varchar(255), term_source bigint not null, primary key (id), unique (scientific_name, term_source)) type=InnoDB;
create table organism_additional_organism_name_collection (organism_collection bigint not null, additional_organism_name_collection bigint not null, primary key (organism_collection, additional_organism_name_collection)) type=InnoDB;
create table parameter (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), name varchar(254), default_value_id bigint, protocol bigint not null, primary key (id), unique (name, protocol)) type=InnoDB;
create table parameter_value (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), unit varchar(254), value varchar(254), parameter bigint, protocol_application bigint, primary key (id)) type=InnoDB;
create table payment_mechanism (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), name varchar(254), primary key (id)) type=InnoDB;
create table personorganization (person_id bigint not null, organization_id bigint not null, primary key (person_id, organization_id)) type=InnoDB;
create table probe_group (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), name varchar(255), array_design_details bigint not null, primary key (id)) type=InnoDB;
create table probeannotation (discriminator varchar(31) not null, id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), stop bigint, strand varchar(255), uniprot_id varchar(255), start bigint, allelea varchar(255), alleleb varchar(255), chromosome integer, dbsnpid varchar(255), flank varchar(255), physical_position bigint, dbsnpversion integer, expression_array_reporter bigint, gene bigint, snp_array_reporter bigint, exon_array_reporter bigint, primary key (id)) type=InnoDB;
create table probefeature (physical_probe_id bigint not null, feature_id bigint not null, primary key (physical_probe_id, feature_id)) type=InnoDB;
create table project (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), status varchar(255) not null, last_updated datetime, public_id_locked bit not null, use_tcga_policy bit not null, host_profile bigint unique, public_profile bigint unique, experiment bigint unique, primary key (id)) type=InnoDB;
create table protocol (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), url varchar(254), contact varchar(254), hardware varchar(254), software varchar(254), name varchar(254) not null, description text, source bigint not null, type bigint not null, primary key (id), unique (name, source)) type=InnoDB;
create table protocol_application (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), notes varchar(255), protocol bigint, array_data bigint, image bigint, primary key (id)) type=InnoDB;
create table publication (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), publication varchar(254), authors varchar(254), doi varchar(254), pub_med_id varchar(254), issue varchar(254), pages varchar(254), publisher varchar(254), uri varchar(254), volume varchar(254), year varchar(254), title varchar(254), editor varchar(254), type bigint, status bigint, experiment bigint, primary key (id)) type=InnoDB;
create table qualitycontroltype (experiment_id bigint not null, term_id bigint not null, primary key (experiment_id, term_id)) type=InnoDB;
create table quantitation_type (id bigint not null auto_increment, bigid varchar(254), name varchar(254), type varchar(254), primary key (id)) type=InnoDB;
create table rawarraydata_hybridizations (rawarraydata_id bigint not null, hybridization_id bigint not null, primary key (rawarraydata_id, hybridization_id)) type=InnoDB;
create table registration_request (id bigint not null auto_increment, role varchar(200) not null, city varchar(50) not null, email varchar(50) not null, fax varchar(25), phone varchar(25) not null, first_name varchar(30) not null, last_name varchar(50) not null, login_name varchar(30), middle_initial varchar(1), organization varchar(200) not null, address1 varchar(200) not null, address2 varchar(200), province varchar(50), zip varchar(10) not null, state bigint, country bigint not null, primary key (id)) type=InnoDB;
create table replicatetype (experiment_id bigint not null, term_id bigint not null, primary key (experiment_id, term_id)) type=InnoDB;
create table sampleextract (sample_id bigint not null, extract_id bigint not null, primary key (sample_id, extract_id)) type=InnoDB;
create table sourceprovider (source_id bigint not null, contact_id bigint not null, primary key (source_id, contact_id)) type=InnoDB;
create table sourcesample (source_id bigint not null, sample_id bigint not null, primary key (source_id, sample_id)) type=InnoDB;
create table state (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), code varchar(255) unique, name varchar(255), primary key (id)) type=InnoDB;
create table term (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), url varchar(254), accession varchar(254), value varchar(254) not null, description varchar(254), source bigint not null, primary key (id), unique (accession, source), unique (value, source)) type=InnoDB;
create table term_categories (term_id bigint not null, category_id bigint not null, primary key (term_id, category_id)) type=InnoDB;
create table term_source (id bigint not null auto_increment, bigid varchar(254), lsid_authority varchar(254), lsid_namespace varchar(254), lsid_object_id varchar(254), url varchar(254), name varchar(254) not null, version varchar(254), primary key (id), unique (name, version), unique (url, version)) type=InnoDB;
create table validation_message (id bigint not null auto_increment, message text, type varchar(10) not null, file_column integer, file_line integer, primary key (id)) type=InnoDB;
alter table access_profile add index FK5B7C41CE3087E349 (project_id), add constraint FK5B7C41CE3087E349 foreign key (project_id) references project (id);
alter table access_profile add index FK5B7C41CE2582790E (group_id), add constraint FK5B7C41CE2582790E foreign key (group_id) references collaborator_group (id);
alter table access_profile_samples add index FKCA737A988CBF7DEB (access_profile_id), add constraint FKCA737A988CBF7DEB foreign key (access_profile_id) references access_profile (id);
alter table access_profile_samples add index FKCA737A98E7C14582 (sample_id), add constraint FKCA737A98E7C14582 foreign key (sample_id) references biomaterial (id);
alter table array add index array_production_idk (production), add constraint array_production_idk foreign key (production) references protocol_application (id);
alter table array add index array_group_idk (array_group), add constraint array_group_idk foreign key (array_group) references array_group (id);
alter table array add index array_design_idk (design), add constraint array_design_idk foreign key (design) references array_design (id);
alter table array_design add index arraydesign_substrae_fk (substrate_type), add constraint arraydesign_substrae_fk foreign key (substrate_type) references term (id);
alter table array_design add index arraydesign_details_fk (design_details), add constraint arraydesign_details_fk foreign key (design_details) references array_design_details (id);
alter table array_design add index arraydesign_provider_fk (provider), add constraint arraydesign_provider_fk foreign key (provider) references contact (id);
alter table array_design add index arraydesign_technology_fk (technology_type), add constraint arraydesign_technology_fk foreign key (technology_type) references term (id);
alter table array_design add index arraydesign_surface_fk (surface_type), add constraint arraydesign_surface_fk foreign key (surface_type) references term (id);
alter table array_design add index arraydesign_organism_fk (organism), add constraint arraydesign_organism_fk foreign key (organism) references organism (id);
alter table array_design add index arraydesign_printing_fk (printing), add constraint arraydesign_printing_fk foreign key (printing) references protocol_application (id);
alter table array_design add index arraydesign_polymer_fk (polymer_type), add constraint arraydesign_polymer_fk foreign key (polymer_type) references term (id);
alter table array_design add index annotation_file_fk (annotation_file), add constraint annotation_file_fk foreign key (annotation_file) references caarrayfile (id);
alter table array_design_design_file add index array_design_fk (array_design), add constraint array_design_fk foreign key (array_design) references array_design (id);
alter table array_design_design_file add index design_file_fk (design_file), add constraint design_file_fk foreign key (design_file) references caarrayfile (id);
alter table arraydata add index arraydata_file_fk (data_file), add constraint arraydata_file_fk foreign key (data_file) references caarrayfile (id);
alter table arraydata add index FKAB188D835936289D (data_set), add constraint FKAB188D835936289D foreign key (data_set) references data_set (id);
alter table arraydata add index arraydata_type_fk (type), add constraint arraydata_type_fk foreign key (type) references array_data_type (id);
alter table arraydatatype_quantitationtypes add index arraydatatype_quantitationtypes_arraydatatype_fk (arraydatatype_id), add constraint arraydatatype_quantitationtypes_arraydatatype_fk foreign key (arraydatatype_id) references array_data_type (id);
alter table arraydatatype_quantitationtypes add index arraydatatype_quantitationtypes_quantitationtype_fk (quantitationtype_id), add constraint arraydatatype_quantitationtypes_quantitationtype_fk foreign key (quantitationtype_id) references quantitation_type (id);
alter table biomaterial add index biomaterial_organism_fk (organism), add constraint biomaterial_organism_fk foreign key (organism) references organism (id);
alter table biomaterial add index biomaterial_dis_state_fk (disease_state), add constraint biomaterial_dis_state_fk foreign key (disease_state) references term (id);
alter table biomaterial add index biomaterial_label_fk (label), add constraint biomaterial_label_fk foreign key (label) references term (id);
alter table biomaterial add index biomaterial_mat_type_fk (material_type), add constraint biomaterial_mat_type_fk foreign key (material_type) references term (id);
alter table biomaterial add index biomaterial_cell_type_fk (cell_type), add constraint biomaterial_cell_type_fk foreign key (cell_type) references term (id);
alter table biomaterial add index biomaterial_site_fk (tissue_site), add constraint biomaterial_site_fk foreign key (tissue_site) references term (id);
alter table biomaterial_protocol_application add index biomaterial_protocol_application_protocol_application_fk (protocol_application), add constraint biomaterial_protocol_application_protocol_application_fk foreign key (protocol_application) references protocol_application (id);
alter table biomaterial_protocol_application add index biomaterial_protocol_application_bio_material_fk (bio_material), add constraint biomaterial_protocol_application_bio_material_fk foreign key (bio_material) references biomaterial (id);
alter table caarrayfile add index caarrayfile_project_fk (project), add constraint caarrayfile_project_fk foreign key (project) references project (id);
alter table caarrayfile add index caarrayfile_validation_result_fk (validation_result), add constraint caarrayfile_validation_result_fk foreign key (validation_result) references file_validation_result (id);
alter table caarrayfile_blob_parts add index FK3BF8C046E313AEE3 (blob_parts), add constraint FK3BF8C046E313AEE3 foreign key (blob_parts) references blob_holder (id);
alter table caarrayfile_blob_parts add index FK3BF8C046F1EACA38 (caarrayfile), add constraint FK3BF8C046F1EACA38 foreign key (caarrayfile) references caarrayfile (id);
alter table category add index FK302BCFEE8803D0E (source), add constraint FK302BCFEE8803D0E foreign key (source) references term_source (id);
alter table category_parents add index FK9BB292C846D88946 (category_id), add constraint FK9BB292C846D88946 foreign key (category_id) references category (id);
alter table category_parents add index FK9BB292C8B9264131 (parent_category_id), add constraint FK9BB292C8B9264131 foreign key (parent_category_id) references category (id);
alter table characteristic add index characteristic_biomaterial_fk (bio_material), add constraint characteristic_biomaterial_fk foreign key (bio_material) references biomaterial (id);
alter table characteristic add index FK15D5819BEE329A48 (category), add constraint FK15D5819BEE329A48 foreign key (category) references category (id);
alter table characteristic_measurement add index characteristic_measurement_unit_fk (unit), add constraint characteristic_measurement_unit_fk foreign key (unit) references term (id);
alter table characteristic_measurement add index FKDCD02B18C776BCA4 (characteristic_id), add constraint FKDCD02B18C776BCA4 foreign key (characteristic_id) references characteristic (id);
alter table characteristic_term add index characteristic_term_term_fk (term), add constraint characteristic_term_term_fk foreign key (term) references term (id);
alter table characteristic_term add index FK76634490C776BCA4 (characteristic_id), add constraint FK76634490C776BCA4 foreign key (characteristic_id) references characteristic (id);
alter table contact add index contact_address_fk (address), add constraint contact_address_fk foreign key (address) references address (id);
alter table data_set add index DATASET_DESIGNELEMENTLIST_FK (design_element_list), add constraint DATASET_DESIGNELEMENTLIST_FK foreign key (design_element_list) references design_element_list (id);
alter table data_set_hybridization_data_list add index FKDC0ABF8A96149A26 (hybridization_data_list), add constraint FKDC0ABF8A96149A26 foreign key (hybridization_data_list) references hybridization_data (id);
alter table data_set_hybridization_data_list add index FKDC0ABF8A5936289D (data_set), add constraint FKDC0ABF8A5936289D foreign key (data_set) references data_set (id);
alter table datacolumn add index column_hybridizationdata_fk (hybridization_data), add constraint column_hybridizationdata_fk foreign key (hybridization_data) references hybridization_data (id);
alter table datacolumn add index column_quantitationtype_fk (quantitation_type), add constraint column_quantitationtype_fk foreign key (quantitation_type) references quantitation_type (id);
alter table datacolumn_blob_parts add index FKA09E0DDD964C4BEA (datacolumn), add constraint FKA09E0DDD964C4BEA foreign key (datacolumn) references datacolumn (id);
alter table datacolumn_blob_parts add index FKA09E0DDDE313AEE3 (blob_parts), add constraint FKA09E0DDDE313AEE3 foreign key (blob_parts) references blob_holder (id);
alter table datasetquantitationtype add index quantitationtype_fk (quantitationtype_id), add constraint quantitationtype_fk foreign key (quantitationtype_id) references quantitation_type (id);
alter table datasetquantitationtype add index dataset_fk (dataset_id), add constraint dataset_fk foreign key (dataset_id) references data_set (id);
alter table derivedarraydata_derivedfrom add index derivedfrom_derivedarraydata_fk (derivedfrom_arraydata_id), add constraint derivedfrom_derivedarraydata_fk foreign key (derivedfrom_arraydata_id) references arraydata (id);
alter table derivedarraydata_derivedfrom add index derivedfrom_arraydata_fk (derivedarraydata_id), add constraint derivedfrom_arraydata_fk foreign key (derivedarraydata_id) references arraydata (id);
alter table derivedarraydata_hybridizations add index derivedarraydata_hybridizations_derivedarraydata_fk (hybridization_id), add constraint derivedarraydata_hybridizations_derivedarraydata_fk foreign key (hybridization_id) references hybridization (id);
alter table derivedarraydata_hybridizations add index derivedarraydata_hybridizations_hybridization_fk (derivedarraydata_id), add constraint derivedarraydata_hybridizations_hybridization_fk foreign key (derivedarraydata_id) references arraydata (id);
create index ap_name_idx on design_element (name);
alter table design_element add index logicalprobe_details_fk (logicalprobe_details_id), add constraint logicalprobe_details_fk foreign key (logicalprobe_details_id) references array_design_details (id);
alter table design_element add index physicalprobe_controltype_fk (control_type), add constraint physicalprobe_controltype_fk foreign key (control_type) references term (id);
alter table design_element add index FK355E97B13B9341B (annotation), add constraint FK355E97B13B9341B foreign key (annotation) references probeannotation (id);
alter table design_element add index probe_group_fk (probe_group), add constraint probe_group_fk foreign key (probe_group) references probe_group (id);
alter table design_element add index physicalprobe_details_fk (physicalprobe_details_id), add constraint physicalprobe_details_fk foreign key (physicalprobe_details_id) references array_design_details (id);
alter table design_element add index feature_details_fk (feature_details_id), add constraint feature_details_fk foreign key (feature_details_id) references array_design_details (id);
alter table designelementlist_designelement add index deldedesignelementlist_fk (designelementlist_id), add constraint deldedesignelementlist_fk foreign key (designelementlist_id) references design_element_list (id);
alter table designelementlist_designelement add index deldedesignelement_fk (designelement_id), add constraint deldedesignelement_fk foreign key (designelement_id) references design_element (id);
alter table experiment add index experiment_payment_mechanism_fk (payment_mechanism), add constraint experiment_payment_mechanism_fk foreign key (payment_mechanism) references payment_mechanism (id);
alter table experiment add index experiment_organism_fk (organism), add constraint experiment_organism_fk foreign key (organism) references organism (id);
alter table experiment add index experiment_manufacturer_fk (manufacturer), add constraint experiment_manufacturer_fk foreign key (manufacturer) references contact (id);
alter table experiment_contact add index experimentcontact_contact_fk (contact), add constraint experimentcontact_contact_fk foreign key (contact) references contact (id);
alter table experiment_contact add index expcontact_invest_fk (experiment), add constraint expcontact_invest_fk foreign key (experiment) references experiment (id);
alter table experiment_design_types add index FKB9EE67BAE05D3086 (term_id), add constraint FKB9EE67BAE05D3086 foreign key (term_id) references term (id);
alter table experiment_design_types add index FKB9EE67BA52C07E0B (experiment_id), add constraint FKB9EE67BA52C07E0B foreign key (experiment_id) references experiment (id);
alter table experimentarraydesign add index investarraydesign_arraydesign_fk (arraydesign_id), add constraint investarraydesign_arraydesign_fk foreign key (arraydesign_id) references array_design (id);
alter table experimentarraydesign add index investarraydesign_invest_fk (experiment_id), add constraint investarraydesign_invest_fk foreign key (experiment_id) references experiment (id);
alter table experimentcontactrole add index investcont_role_fk (role_id), add constraint investcont_role_fk foreign key (role_id) references term (id);
alter table experimentcontactrole add index investcont_contact_fk (experimentcontact_id), add constraint investcont_contact_fk foreign key (experimentcontact_id) references experiment_contact (id);
alter table experimentextract add index experimentextract_extract_fk (extract_id), add constraint experimentextract_extract_fk foreign key (extract_id) references biomaterial (id);
alter table experimentextract add index experimentextract_invest_fk (experiment_id), add constraint experimentextract_invest_fk foreign key (experiment_id) references experiment (id);
alter table experimentlabeledextract add index experimentle_le_fk (labeled_extract_id), add constraint experimentle_le_fk foreign key (labeled_extract_id) references biomaterial (id);
alter table experimentlabeledextract add index experimentle_invest_fk (experiment_id), add constraint experimentle_invest_fk foreign key (experiment_id) references experiment (id);
alter table experimentsample add index experimentsample_invest_fk (experiment_id), add constraint experimentsample_invest_fk foreign key (experiment_id) references experiment (id);
alter table experimentsample add index experimentsample_sample_fk (sample_id), add constraint experimentsample_sample_fk foreign key (sample_id) references biomaterial (id);
alter table experimentsource add index experimentsource_invest_fk (experiment_id), add constraint experimentsource_invest_fk foreign key (experiment_id) references experiment (id);
alter table experimentsource add index experimentsource_source_fk (source_id), add constraint experimentsource_source_fk foreign key (source_id) references biomaterial (id);
alter table extractlabeledextract add index extractlabeled_labeled_fk (labeledextract_id), add constraint extractlabeled_labeled_fk foreign key (labeledextract_id) references biomaterial (id);
alter table extractlabeledextract add index extractlabeled_extract_fk (extract_id), add constraint extractlabeled_extract_fk foreign key (extract_id) references biomaterial (id);
alter table factor add index factor_type_fk (type), add constraint factor_type_fk foreign key (type) references term (id);
alter table factor add index factor_experiment_fk (experiment), add constraint factor_experiment_fk foreign key (experiment) references experiment (id);
alter table factor_value add index factorvalue_factor_fk (factor), add constraint factorvalue_factor_fk foreign key (factor) references factor (id);
alter table factor_value add index factorvalue_hybridizatation_fk (hybridization), add constraint factorvalue_hybridizatation_fk foreign key (hybridization) references hybridization (id);
alter table factor_value add index factorvalue_unit_fk (unit), add constraint factorvalue_unit_fk foreign key (unit) references term (id);
alter table file_validation_result_message_set add index FK2746A90B24BD8119 (file_validation_result), add constraint FK2746A90B24BD8119 foreign key (file_validation_result) references file_validation_result (id);
alter table file_validation_result_message_set add index FK2746A90B48F7BFF1 (message_set), add constraint FK2746A90B48F7BFF1 foreign key (message_set) references validation_message (id);
alter table hybridization add index hybridization_array_fk (array), add constraint hybridization_array_fk foreign key (array) references array (id);
alter table hybridization add index hybridizationamount_unit_fk (amount_of_material_unit), add constraint hybridizationamount_unit_fk foreign key (amount_of_material_unit) references term (id);
alter table hybridization add index hybridization_expr_fk (experiment), add constraint hybridization_expr_fk foreign key (experiment) references experiment (id);
alter table hybridization_data add index hybridizationdata_labeledextract_fk (labeled_extract), add constraint hybridizationdata_labeledextract_fk foreign key (labeled_extract) references biomaterial (id);
alter table hybridization_data add index hybridizationdata_hybridization_fk (hybridization), add constraint hybridizationdata_hybridization_fk foreign key (hybridization) references hybridization (id);
alter table hybridization_data add index hybridizationdata_dataset_fk (data_set), add constraint hybridizationdata_dataset_fk foreign key (data_set) references data_set (id);
alter table hybridization_data_columns add index FKFE89583F6109494B (hybridization_data), add constraint FKFE89583F6109494B foreign key (hybridization_data) references hybridization_data (id);
alter table hybridization_data_columns add index FKFE89583F67C60847 (columns), add constraint FKFE89583F67C60847 foreign key (columns) references datacolumn (id);
alter table hybridization_protocol_application add index hybridization_protocol_application_protocol_application_fk (protocol_application), add constraint hybridization_protocol_application_protocol_application_fk foreign key (protocol_application) references protocol_application (id);
alter table hybridization_protocol_application add index hybridization_protocol_application_hybridization_fk (hybridization), add constraint hybridization_protocol_application_hybridization_fk foreign key (hybridization) references hybridization (id);
alter table image add index image_file_fk (image_file), add constraint image_file_fk foreign key (image_file) references caarrayfile (id);
alter table image add index image_hybridization_fk (hybridization), add constraint image_hybridization_fk foreign key (hybridization) references hybridization (id);
alter table image add index image_rawarraydata_fk (raw_array_data), add constraint image_rawarraydata_fk foreign key (raw_array_data) references arraydata (id);
alter table labeledextracthybridization add index labeledextracthybridization_hybridization_fk (hybridization_id), add constraint labeledextracthybridization_hybridization_fk foreign key (hybridization_id) references hybridization (id);
alter table labeledextracthybridization add index labeledextracthybridization_labeledextract_fk (labeledextract_id), add constraint labeledextracthybridization_labeledextract_fk foreign key (labeledextract_id) references biomaterial (id);
alter table logicalprobe_physicalprobe add index FKE80BA841AF48BA (physical_probe_id), add constraint FKE80BA841AF48BA foreign key (physical_probe_id) references design_element (id);
alter table logicalprobe_physicalprobe add index FKE80BA841C0C30D98 (logical_probe_id), add constraint FKE80BA841C0C30D98 foreign key (logical_probe_id) references design_element (id);
alter table normalizationtype add index normtype_term_fk (term_id), add constraint normtype_term_fk foreign key (term_id) references term (id);
alter table normalizationtype add index normtype_invest_fk (experiment_id), add constraint normtype_invest_fk foreign key (experiment_id) references experiment (id);
alter table organism add index FK4E7680D2A3E46441 (term_source), add constraint FK4E7680D2A3E46441 foreign key (term_source) references term_source (id);
alter table organism_additional_organism_name_collection add index FK993B3790B8FC7DBB (additional_organism_name_collection), add constraint FK993B3790B8FC7DBB foreign key (additional_organism_name_collection) references additional_organism_name (id);
alter table organism_additional_organism_name_collection add index FK993B37903D9DBB77 (organism_collection), add constraint FK993B37903D9DBB77 foreign key (organism_collection) references organism (id);
alter table parameter add index parameter_protocol_fk (protocol), add constraint parameter_protocol_fk foreign key (protocol) references protocol (id);
alter table parameter add index parameter_defaultvalue_fk (default_value_id), add constraint parameter_defaultvalue_fk foreign key (default_value_id) references parameter_value (id);
alter table parameter_value add index paramvalue_protocolapp_fk (protocol_application), add constraint paramvalue_protocolapp_fk foreign key (protocol_application) references protocol_application (id);
alter table parameter_value add index paramvalue_parameter_fk (parameter), add constraint paramvalue_parameter_fk foreign key (parameter) references parameter (id);
alter table personorganization add index perorg_person_fk (person_id), add constraint perorg_person_fk foreign key (person_id) references contact (id);
alter table personorganization add index perorg_organization_fk (organization_id), add constraint perorg_organization_fk foreign key (organization_id) references contact (id);
alter table probe_group add index FK81749D30B924C863 (array_design_details), add constraint FK81749D30B924C863 foreign key (array_design_details) references array_design_details (id);
alter table probeannotation add index FKA31DD6DFD9460E1 (snp_array_reporter), add constraint FKA31DD6DFD9460E1 foreign key (snp_array_reporter) references arrayreporter (id);
alter table probeannotation add index FKA31DD6DFE03366E5 (expression_array_reporter), add constraint FKA31DD6DFE03366E5 foreign key (expression_array_reporter) references arrayreporter (id);
alter table probeannotation add index FKA31DD6DF4043901B (gene), add constraint FKA31DD6DF4043901B foreign key (gene) references gene (id);
alter table probeannotation add index FKA31DD6DFC462B731 (exon_array_reporter), add constraint FKA31DD6DFC462B731 foreign key (exon_array_reporter) references arrayreporter (id);
alter table probefeature add index FK1B13AD46AF48BA (physical_probe_id), add constraint FK1B13AD46AF48BA foreign key (physical_probe_id) references design_element (id);
alter table probefeature add index FK1B13AD463C971A69 (feature_id), add constraint FK1B13AD463C971A69 foreign key (feature_id) references design_element (id);
alter table project add index project_hostaccess_fk (host_profile), add constraint project_hostaccess_fk foreign key (host_profile) references access_profile (id);
alter table project add index project_experiment_fk (experiment), add constraint project_experiment_fk foreign key (experiment) references experiment (id);
alter table project add index project_publicaccess_fk (public_profile), add constraint project_publicaccess_fk foreign key (public_profile) references access_profile (id);
alter table protocol add index protocol_term_source_fk (source), add constraint protocol_term_source_fk foreign key (source) references term_source (id);
alter table protocol add index protocol_type_fk (type), add constraint protocol_type_fk foreign key (type) references term (id);
alter table protocol_application add index protocolapp_arraydata_fk (array_data), add constraint protocolapp_arraydata_fk foreign key (array_data) references arraydata (id);
alter table protocol_application add index protocolapp_protocol (protocol), add constraint protocolapp_protocol foreign key (protocol) references protocol (id);
alter table protocol_application add index protocolapp_image_fk (image), add constraint protocolapp_image_fk foreign key (image) references image (id);
alter table publication add index publication_type_fk (type), add constraint publication_type_fk foreign key (type) references term (id);
alter table publication add index publication_expr_fk (experiment), add constraint publication_expr_fk foreign key (experiment) references experiment (id);
alter table publication add index publication_status_fk (status), add constraint publication_status_fk foreign key (status) references term (id);
alter table qualitycontroltype add index qualctrltype_term_fk (term_id), add constraint qualctrltype_term_fk foreign key (term_id) references term (id);
alter table qualitycontroltype add index qualctrltype_invest_fk (experiment_id), add constraint qualctrltype_invest_fk foreign key (experiment_id) references experiment (id);
alter table rawarraydata_hybridizations add index rawarraydata_hybridizations_rawarraydata_fk (hybridization_id), add constraint rawarraydata_hybridizations_rawarraydata_fk foreign key (hybridization_id) references hybridization (id);
alter table rawarraydata_hybridizations add index rawarraydata_hybridizations_hybridization_fk (rawarraydata_id), add constraint rawarraydata_hybridizations_hybridization_fk foreign key (rawarraydata_id) references arraydata (id);
alter table registration_request add index registrationrequest_country_fk (country), add constraint registrationrequest_country_fk foreign key (country) references country (id);
alter table registration_request add index registrationrequest_state_fk (state), add constraint registrationrequest_state_fk foreign key (state) references state (id);
alter table replicatetype add index repltype_term_fk (term_id), add constraint repltype_term_fk foreign key (term_id) references term (id);
alter table replicatetype add index repltype_invest_fk (experiment_id), add constraint repltype_invest_fk foreign key (experiment_id) references experiment (id);
alter table sampleextract add index sampleextract_extract_fk (extract_id), add constraint sampleextract_extract_fk foreign key (extract_id) references biomaterial (id);
alter table sampleextract add index sampleextract_sample_fk (sample_id), add constraint sampleextract_sample_fk foreign key (sample_id) references biomaterial (id);
alter table sourceprovider add index sourceprovider_provider_fk (contact_id), add constraint sourceprovider_provider_fk foreign key (contact_id) references contact (id);
alter table sourceprovider add index sourceprovider_source_fk (source_id), add constraint sourceprovider_source_fk foreign key (source_id) references biomaterial (id);
alter table sourcesample add index sourcesample_source_fk (source_id), add constraint sourcesample_source_fk foreign key (source_id) references biomaterial (id);
alter table sourcesample add index sourcesample_sample_fk (sample_id), add constraint sourcesample_sample_fk foreign key (sample_id) references biomaterial (id);
alter table term add index FK36446CE8803D0E (source), add constraint FK36446CE8803D0E foreign key (source) references term_source (id);
alter table term_categories add index FKDF0E9BCFE05D3086 (term_id), add constraint FKDF0E9BCFE05D3086 foreign key (term_id) references term (id);
alter table term_categories add index FKDF0E9BCF46D88946 (category_id), add constraint FKDF0E9BCF46D88946 foreign key (category_id) references category (id);
